var coursedb = {
	'cn': {
		'cs101' : {
			'enabled':true,
			'online':false,
			'cid':'CS101',
			'sname':'Minecraft World Building',
			'curriculum':'minecraft1',
			'title1':'Minecraft世界开发与编程',
			'title2':'图形化编程入基础',
			'name':'Minecraft世界开发与编程:图形化编程入基础',
			'shortName':'Minecraft世界开发与编程',
			'imageUrl':'img/my/minecraftbasic/bg-sm.jpg',
			'gradeLevel':'L1图形化编程',
			'text':'在Minecraft游戏中学习3D建模、控制指令与图形编程初步',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'mcbuildc.html',
			'locations':'选择地点',
			'registerUrl':'corncn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs101p' : {
			'enabled':false,
			'online':false,
			'cid':'CS101p',
			'sname':'Minecraft MakeCode Project',
			'curriculum':'',
			'title1':'Minecraft世界开发与指令编程',
			'title2':'项目开发',
			'name':'Minecraft世界开发与指令编程:项目开发',
			'shortName':'Minecraft世界开发与指令编程:项目开发',
			'imageUrl':'img/my/minecraftbasic/bg-sm.jpg',
			'gradeLevel':'L1图形化编程',
			'text':'在Minecraft游戏中学习3D建模、控制指令与图形编程初步（项目开发）',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'mcbuildc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs110' : {
			'enabled':true,
			'online':false,
			'cid':'CS110',
			'sname':'Minecraft AI',
			'curriculum':'minecraft1',
			'title1':'少儿AI编程Minecraft',
			'title2':'图形化编程入基础',
			'name':'Minecraft世界开发与编程:学习实践AI基础',
			'shortName':'少儿AI编程Minecraft',
			'imageUrl':'img/my/minecode/mcai.jpg',
			'gradeLevel':'L1图形化编程',
			'text':'在Minecraft游戏中学习AI在游戏中的初步应用，学习开发第一个人工智能程序',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'mcbuildc.html',
			'locations':'选择地点',
			'registerUrl':'corncn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},		
		'cs130' : {
			'enabled':true,
			'online':false,
			'cid':'CS130',
			'sname':'Minecraft MakeCode',
			'curriculum':'minecraft1',
			'title1':'Minecraft创新编程与实践',
			'title2':'用最流行的游戏学编程',
			'name':'Minecraft创新编程与实践:用最流行的游戏学编程',
			'shortName':'Minecraft创新编程与实践',
			'imageUrl':'img/my/minecode/minecodebgsm.jpg',
			'gradeLevel':'L1图形化编程',
			'text':'在Minecraft我的世界游戏中学习编程将是孩子们理想的学习体验',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'minecodec.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs140' : {
			'enabled':true,
			'online':false,
			'cid':'CS140',
			'sname':'SPRK Robotics',
			'curriculum':'',
			'title1':'和SPRK机器人一起学习编程',
			'title2':'带领你的机器人完成挑战',
			'name':'和SPRK机器人一起学习编程:带领你的机器人完成挑战',
			'shortName':'和SPRK机器人一起学习编程',
			'imageUrl':'img/my/sprk-learn-5sm.jpg',
			'gradeLevel':'L1图形化编程',
			'text':'学习如何通过编程控制SPRK机器人，打开神奇计算机编程世界的大门',
			'tag':'机器人编程系列',
			'pathway':['robot'],
			'detailsTitle':'查看详情',
			'detailsUrl':'sprkc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},		
		'cs150' : {
			'enabled':true,
			'online':false,
			'cid':'CS150',
			'sname':'Lego Robotics 1',
			'curriculum':'',
			'title1':'Lego MindStorms机器人编程挑战',
			'title2':'挑战不可能的任务',
			'name':'Lego MindStorms机器人编程挑战:挑战不可能的任务',
			'shortName':'Lego机器人编程挑战',
			'imageUrl':'img/my/lego/lego-bg-sm.jpg',
			'gradeLevel':'L1图形化编程',
			'text':'在控制机器人挑战自己过程中学习编程,将是你从未尝试过的学习体验',
			'tag':'机器人编程系列',
			'pathway':['robot'],
			'detailsTitle':'查看详情',
			'detailsUrl':'legoc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs151p' : {
			'enabled':false,
			'online':false,
			'cid':'CS151p',
			'sname':'Lego Robotics Project',
			'curriculum':'',
			'title1':'Lego MindStorms机器人编程挑战',
			'title2':'项目实践',
			'name':'Lego MindStorms机器人编程挑战:项目实践',
			'shortName':'Lego机器人编程挑战:项目实践',
			'imageUrl':'img/my/lego/lego-bg-sm.jpg',
			'gradeLevel':'L1图形化编程',
			'text':'在控制机器人挑战自己过程中学习编程,将是你从未尝试过的学习体验',
			'tag':'机器人编程系列',
			'pathway':['robot'],
			'detailsTitle':'查看详情',
			'detailsUrl':'legoc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs160' : {
			'enabled':true,
			'online':false,
			'cid':'CS160',
			'sname':'Scratch 1',
			'curriculum':'',
			'title1':'MIT Scratch创新编程与实践',
			'title2':'做你自己的游戏、动画、多媒体',
			'name':'MIT Scratch创新编程与实践:做你自己的游戏、动画、多媒体',
			'shortName':'MIT Scratch创新编程与实践',
			'imageUrl':'img/my/scratch/scratchbg.png',
			'gradeLevel':'L1图形化编程',
			'text':'学Scratch编程，发挥你的创造力，和来自世界各地的小程序员分享你的作品',
			'tag':'游戏编程系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'scratchc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs170' : {
			'enabled':true,
			'online':false,
			'cid':'CS170',
			'sname':'Scratch 2',
			'curriculum':'',
			'title1':'MIT Scratch编程高阶',
			'title2':'做你自己的游戏、动画、多媒体',
			'name':'MIT Scratch编程高阶:做你自己的游戏、动画、多媒体',
			'shortName':'MIT Scratch编程高阶',
			'imageUrl':'img/my/scratch/scratch2.jpg',
			'gradeLevel':'L1图形化编程',
			'text':'学Scratch编程，发挥你的创造力，和来自世界各地的小程序员分享你的作品',
			'tag':'游戏编程系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'scratch2c.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs200' : {
			'enabled':true,
			'online':false,
			'cid':'CS200',
			'sname':'Minecraft JavaScript',
			'curriculum':'minecraft1',
			'title1':'Javascript编程初步',
			'title2':'Minecraft MakeCode编程',
			'name':'Javascript编程初步: Minecraft MakeCode编程',
			'shortName':'Javascript编程初步MakeCode',
			'imageUrl':'img/my/minecraftbasic/bg2-sm.jpg',
			'gradeLevel':'L2简洁代码编程',
			'text':'在微软的MakeCode平台中学习Javscript的基础，开始代码编程之路',
			'tag':'游戏编程系列',
			'pathway':['coding', 'game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'mcbuild2c.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs210' : {
			'enabled':true,
			'online':false,
			'cid':'CS210',
			'sname':'MicroBit',
			'curriculum':'',
			'title1':'Javascript编程进阶',
			'title2':'MicroBit电子电路编程',
			'name':'Javascript编程进阶: MicroBit电子电路编程',
			'shortName':'Javascript编程进阶MicroBit',
			'imageUrl':'img/my/microbit/bg.jpg',
			'gradeLevel':'L2简洁代码编程',
			'text':'学习微软最新的MicroBit编程，控制电子小元件，发挥你的创造力，体验编程的神奇',
			'tag':'游戏编程系列',
			'pathway':['hardware'],
			'detailsTitle':'查看详情',
			'detailsUrl':'',
			'locations':'选择地点',
			'registerUrl':'microbit-cn.html',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs201p' : {
			'enabled':false,
			'online':false,
			'cid':'CS201',
			'sname':'MicroBit Project',
			'curriculum':'',
			'title1':'Minecraft创新编程与实践',
			'title2':'项目实践',
			'name':'Minecraft创新编程与实践:项目实践',
			'shortName':'Minecraft创新编程与实践:项目实践',
			'imageUrl':'img/my/minecode/minecodebgsm.jpg',
			'gradeLevel':'4-6年级',
			'text':'在Minecraft我的世界游戏中学习编程将是孩子们理想的学习体验（项目实践）',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'minecodec.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs220' : {
			'enabled':true,
			'online':false,
			'cid':'CS220',
			'sname':'Roblox 1',
			'curriculum':'roblox1',
			'title1':'Roblox游戏开发与Lua编程',
			'title2':'游戏创业学Lua编程',
			'name':'Roblox游戏开发与Lua编程:开发游戏学Lua编程',
			'shortName':'Roblox游戏开发与Lua编程',
			'imageUrl':'img/my/roblox1/bg-sm.jpg',
			'gradeLevel':'L2简洁代码编程',
			'text':'学习开发风靡全球的Roblox，发布你自己的游戏，创业编程两不误',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'roblox1c.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba',
			'completion':'Roblox 1作为L2级别的核心课程，主要的目标是带领同学开始编写相对简洁的代码程序，而不再使用初级的图形化编程。通过本节课的完成，同学已经掌握了基本Lua程序代码的语法和控制流程，并且完成了一个初步的Roblox的游戏项目，为下一阶段的高级Lua编程打下良好的基础。',
			'nextCourseId':'CS230'
		}, 		
		'cs220p' : {
			'enabled':false,
			'online':false,
			'cid':'CS220p',
			'sname':'Roblox 1 Project',
			'curriculum':'roblox1',
			'title1':'Roblox游戏开发与Lua编程进阶',
			'title2':'项目实践',
			'name':'Roblox游戏开发与发布:项目实践',
			'shortName':'Roblox游戏开发与发布:项目实践',
			'imageUrl':'img/my/roblox1/bg-sm.jpg',
			'gradeLevel':'L2简洁代码编程',
			'text':'学习开发风靡全球的Roblox，发布你自己的游戏，创业编程两不误（项目实践）',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'roblox1c.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs230' : {
			'enabled':true,
			'online':false,
			'cid':'CS230',
			'sname':'Roblox 2',
			'curriculum':'roblox2',
			'title1':'Roblox游戏开发与Lua编程进阶',
			'title2':'游戏创业学编程',
			'name':'Roblox游戏开发与Lua编程进阶:游戏创业学编程',
			'shortName':'Roblox游戏开发与Lua编程进阶',
			'imageUrl':'img/my/roblox1/bg2-sm.jpg',
			'gradeLevel':'L2简洁代码编程',
			'text':'学习开发风靡全球的Roblox，发布你自己的游戏，创业编程两不误',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'roblox2c.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba',
			'introduction':'Roblox 2是L2级别的核心课程，主要的目标是让同学使用Lua更多的编写简洁的代码程序，尝试设计程序算法，并且可以独立的构思功能并融入到项目中去。本节课同学需要完成所有常用的Lua编程语言的功能特点，并且完成一个可以参赛的综合的Roblox的游戏项目，为下一阶段L3的编程学习做好准备。',
			'completion':'Roblox 2是L2级别的核心课程，主要的目标是让同学使用Lua更多的编写简洁的代码程序，尝试设计程序算法，并且可以独立的构思功能并融入到项目中去。通过本节课的完成，同学已经完成所有常用的Lua编程语言的功能特点，并且完成了一个可以参赛的综合的Roblox的游戏项目，为下一阶段L3的编程学习做好了准备。',
			'nextCourseId':'CS240'
		},
		'cs240' : {
			'enabled':true,
			'online':false,
			'cid':'CS240',
			'sname':'Roblox 3 Game AI',
			'curriculum':'',
			'title1':'人工智能初步与Lua实践',
			'title2':'AI与智能游戏编程',
			'name':'人工智能初步与Lua实践:AI与智能游戏编程',
			'shortName':'人工智能初步与Lua实践',
			'imageUrl':'img/my/roblox3/bg2-sm.jpg',
			'gradeLevel':'L3代码编程',
			'text':'在Roblox平台开发智能游戏AI，开启AI编程学习的第一步',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'roblox3c.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba',
			'introduction':'从Roblox 3开始，学生计入到L3级别的编程课程，该级别要求同学专注于代码的编程和算法设计与实现。Roblox 3依托Roblox游戏开发平台，主要的目标是让同学使用Lua代码实现初步的AI功能与逻辑。本节课目标是带领同学完成一个AI游戏算法并植入到游戏项目项目中去，打开AI世界的大门。',
			'introduction':'从Roblox 3开始，同学已经计入到L3级别的编程课程，该级别要求同学完全专注于代码的编程和算法设计与实现。通过本节课的完成，同学学习了Lua代码实现初步的AI功能与逻辑，并且完成了一个AI游戏算法并植入到了自己的游戏项目项目中去，对AI世界有了初步的体验。',
			'nextCourseId':'CS300'	
		},
		'cs300' : {
			'enabled':true,
			'online':false,
			'cid':'CS300',
			'sname':'Python 1',
			'curriculum':'python1',
			'title1':'Python编程初步',
			'title2':'学做Minecraft游戏开发员',
			'name':'Python编程初步:学做Minecraft游戏开发员',
			'shortName':'Python编程初步',
			'imageUrl':'img/my/pythonmine/pyminebghp.jpg',
			'gradeLevel':'L3代码编程',
			'text':'在世界最流行的游戏中学习世界最流行的编程语言Python',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'python-minecraftc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba',
			'introduction':'Python 1作为L3级别的第一个核心课程，主要的目标是教授同学使用Python的基本语法与指令，并且能够完成基础的应用程序的开发。通过课程的完成，同学可以掌握Python的基础知识，并且完成一个基础的Python项目，为下一阶段的Python进阶编程打下良好的基础。',
			'completion':'Python 1作为L3级别的第一个核心课程，主要的目标是教授同学使用Python的基本语法与指令，并且能够完成基础的应用程序的开发。通过课程的完成，同学已经掌握了Python的基础知识，并且完成了一个基础的Python项目，为下一阶段的Python进阶编程打下了良好的基础。',
			'nextCourseId':'cs310'
		},
		'cs310p' : {
			'enabled':false,
			'online':false,
			'cid':'CS310p',
			'sname':'Python 1 Project',
			'curriculum':'python1',
			'title1':'Python编程初步',
			'title2':'项目实践I',
			'name':'Python编程初步:项目实践I',
			'shortName':'Python编程初步:项目实践I',
			'imageUrl':'img/my/pythonmine/pyminebghp.jpg',
			'gradeLevel':'L3代码编程',
			'text':'在世界最流行的游戏中学习世界最流行的编程语言Python（项目实践）',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'python-minecraftc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs310' : {
			'enabled':true,
			'online':false,
			'cid':'CS310',
			'sname':'Python 2',
			'curriculum':'python2',
			'title1':'Python编程高阶',
			'title2':'动手编写真正的计算机应用程序',
			'name':'Python编程高阶:动手编写真正的计算机应用程序',
			'shortName':'Python编程高阶',
			'imageUrl':'img/my/python-learn-3.jpg',
			'gradeLevel':'L3代码编程',
			'text':'学习当今最流行的编程语言，开发任何你想制作的应用程序',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'pythonc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba',
			'completion':'Python 2作为L3级别的核心课程，主要的目标是带领同学使用Python进行基本程序算法的设计与实现，并且学习高级数据结构的知识。通过课程的完成，同学已经掌握了Python的数据结构与算法，并且完成了一个综合的Python项目，为下一阶段L4级别的主题应用编程打下了良好的基础。',
			'nextCourseId':'cs430',
			'introduction':'Python 2作为L3级别的高级核心课程，主要的目标是带领同学使用Python进行程序算法的设计与实现，并且学习高级数据结构的知识。通过课程的完成，试同学可以掌握Python的数据结构与算法，并且完成一个综合的Python项目，为下一阶段L4级别的主题应用编程打下良好的基础。'
		},
		'cs320' : {
			'enabled':true,
			'online':false,
			'cid':'CS320',
			'sname':'Python 3',
			'curriculum':'',
			'title1':'数据结构与算法',
			'title2':'数据结构与算法介绍',
			'name':'数据结构与算法:深入了解计算机数据结构与算法原理',
			'shortName':'数据结构与算法',
			'imageUrl':'img/my/python2.jpg',
			'gradeLevel':'L3代码编程',
			'text':'学习编程语言Python的高级算法，解决、优化实际问题',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'pythonc2.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},		
		'cs311p' : {
			'enabled':false,
			'online':false,
			'cid':'CS311p',
			'sname':'Python 2 Project',
			'curriculum':'python2',
			'title1':'Python编程进阶',
			'title2':'项目实践II',
			'name':'Python编程进阶:项目实践II',
			'shortName':'Python编程进阶:项目实践II',
			'imageUrl':'img/my/python2.jpg',
			'gradeLevel':'L3代码编程',
			'text':'学习编程语言Python的高级算法，解决、优化实际问题（项目实践）',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'pythonc2.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs350' : {
			'enabled':true,
			'online':false,
			'cid':'CS350',
			'sname':'Lego Robotics 2',
			'curriculum':'',
			'title1':'Lego机器人进阶之Java编程',
			'title2':'用真正的编程控制机器人',
			'name':'Lego机器人进阶之Java编程:用真正的编程控制机器人',
			'shortName':'Lego机器人进阶之Java编程',
			'imageUrl':'img/my/lego/lego2-bg-sm.jpg',
			'gradeLevel':'L3代码编程',
			'text':'在控制机器人挑战自己过程中学习Java编程,编程变得更加丰富多彩',
			'tag':'机器人编程系列',
			'pathway':['robot'],
			'detailsTitle':'查看详情',
			'detailsUrl':'legoc2.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs360' : {
			'enabled':false,
			'online':false,
			'cid':'CS360',
			'sname':'Lego Robotics 2 Project',
			'curriculum':'',
			'title1':'Lego机器人进阶之高级传感器应用',
			'title2':'做最强机器人',
			'name':'Lego机器人进阶之高级传感器应用:做最强机器人',
			'shortName':'Lego机器人进阶之高级传感器应用',
			'imageUrl':'img/my/lego/lego2-bg-sm.jpg',
			'gradeLevel':'L3代码编程',
			'text':'通过运用所有的Lego机器人传感器完成Lego机器人的最终版本',
			'tag':'机器人编程系列',
			'pathway':['robot'],
			'detailsTitle':'查看详情',
			'detailsUrl':'legoc2.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},		
		'cs400' : {
			'enabled':true,
			'online':false,
			'cid':'CS400',
			'sname':'Thukable',
			'curriculum':'',
			'title1':'MIT手机APP发明家',
			'title2':'动手编写自己的APP做小小创业者',
			'name':'MIT手机APP发明家:动手编写自己的APP做小小创业者',
			'shortName':'MIT手机APP发明家',
			'imageUrl':'img/my/app-dev-2sm.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'厌倦了每天玩自己的手机APP？那就学习动手编程制作自己的手机APP，做下一个年轻的创业者',
			'tag':'移动互联网编程系列',
			'pathway':['mobile'],
			'detailsTitle':'查看详情',
			'detailsUrl':'mobilec.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs410' : {
			'enabled':true,
			'online':false,
			'cid':'CS410',
			'sname':'Unity 1',
			'curriculum':'unity1',
			'title1':'Unity3D游戏开发体验',
			'title2':'从游戏玩家到游戏开发员',
			'name':'Unity3D游戏开发体验:从游戏玩家到游戏开发员',
			'shortName':'Unity3D游戏开发体验',
			'imageUrl':'img/my/unity3d/unity3d-1sm.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习世界最流行的游戏开发引擎，让你在中学就可以挥洒创意，创作出你自己想玩的游戏。',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'unity3dc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs411p' : {
			'enabled':false,
			'online':false,
			'cid':'CS411p',
			'sname':'Unity 1 Project',
			'curriculum':'unity1',
			'title1':'Unity3D游戏开发体验',
			'title2':'项目实践I',
			'name':'Unity3D游戏开发体验:项目实践I',
			'shortName':'Unity3D游戏开发体验:项目实践I',
			'imageUrl':'img/my/unity3d/unity3d-1sm.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习世界最流行的游戏开发引擎，让你在中学就可以挥洒创意，创作出你自己想玩的游戏（项目实践）',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'unity3dc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs420' : {
			'enabled':true,
			'online':false,
			'cid':'CS420',
			'sname':'Unity 2',
			'curriculum':'unity2',
			'title1':'Unity3D游戏开发进阶',
			'title2':'专业游戏游戏开发员养成之路',
			'name':'Unity3D游戏开发进阶:专业游戏游戏开发员养成之路',
			'shortName':'Unity3D游戏开发进阶',
			'imageUrl':'img/my/unity3d/bg-3sm.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习游戏开发引擎的高级技巧和知识，创作专业游戏作品。',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'unity3d2c.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs425' : {
			'enabled':true,
			'online':false,
			'cid':'CS425',
			'sname':'Game AI',
			'curriculum':'',
			'title1':'人工智能与游戏AI设计',
			'title2':'专业游戏游戏开发员养成之路',
			'name':'人工智能与游戏AI设计:专业游戏游戏开发员养成之路',
			'shortName':'人工智能与游戏AI设计',
			'imageUrl':'img/my/unity3d/gameai1.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习游戏开发引擎的高级技巧和知识，创作专业游戏作品。',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'unity3d2c.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs430' : {
			'enabled':true,
			'online':false,
			'cid':'CS430',
			'sname':'AI 1',
			'curriculum':'ai1',
			'title1':'AI人工智能初步与深度学习',
			'title2':'Python高阶编程',
			'name':'Python高阶编程:AI人工智能初步与深度学习',
			'shortName':'AI人工智能初步与深度学习',
			'imageUrl':'img/my/ai-bg.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习人工智能的初步并且动手编写实用的真正的AI应用程序',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'pythonc3ai.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba',
			'introduction':'AI人工智能初步是L4级别的核心课程，主要的目标是让同学开始进行编程的主题应用开发，解决实际的问题，并且可以独立的实际AI算法并融入到项目中去。本节课同学需要完成所有常用的机器学习算法与功能库，并且完成一个可以参赛的综合的AI与数据分析的项目，为下一阶段的AI 2编程做好准备。',
		},
		'cs435' : {
			'enabled':true,
			'online':false,
			'cid':'CS435',
			'sname':'AI 2',
			'curriculum':'ai2',
			'title1':'AI深度学习与区块链技术',
			'title2':'AI高阶编程',
			'name':'AI高阶编程:探索深度学习与区块链技术',
			'shortName':'AI高阶编程',
			'imageUrl':'img/my/ai2/ai2-bg.png',
			'gradeLevel':'L4应用主题编程',
			'text':'学习人工智能的高级知识与应用了解最前沿的技术革新',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'blockchainaic.html',
			'locations':'选择地点',
			'registerUrl':'blockchainaic.html',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},		
		'cs436' : {
			'enabled':true,
			'online':false,
			'cid':'CS436',
			'sname':'Web Scraping',
			'curriculum':'webcr',
			'title1':'网络爬虫与数据分析',
			'title2':'做未来的数据工程师',
			'name':'网络爬虫与数据分析:数据工程的起点',
			'shortName':'网络爬虫与数据分析',
			'imageUrl':'img/my/cewcr/bg-big.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习爬虫算法，获取前沿数据',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'webscraping.html',
			'locations':'选择地点',
			'registerUrl':'webscrapingc.html',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs440' : {
			'enabled':true,
			'online':false,
			'cid':'CS440',
			'sname':'Swift',
			'curriculum':'',
			'title1':'iPhone手机APP开发与Swift编程',
			'title2':'在Apple商店发布你的手机App',
			'name':'iPhone手机APP开发与Swift编程:在Apple商店发布你的手机App',
			'shortName':'iPhone手机APP开发与Swift编程',
			'imageUrl':'img/my/ios/bg-sm.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习流行的Swift编程语言和iOS手机App开发，在你的iPhone上运行自己的App',
			'tag':'移动互联网编程系列',
			'pathway':['mobile'],
			'detailsTitle':'查看详情',
			'detailsUrl':'mobileiosc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs441p' : {
			'enabled':false,
			'online':false,
			'cid':'CS441p',
			'sname':'Swift Project',
			'curriculum':'',
			'title1':'iPhone手机APP开发与Swift编程',
			'title2':'项目实践',
			'name':'iPhone手机APP开发与Swift编程:项目实践',
			'shortName':'iPhone手机APP开发与Swift编程:项目实践',
			'imageUrl':'img/my/ios/bg-sm.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习流行的Swift编程语言和iOS手机App开发，在你的iPhone上运行自己的App（项目实践）',
			'tag':'移动互联网编程系列',
			'pathway':['mobile'],
			'detailsTitle':'查看详情',
			'detailsUrl':'mobileiosc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs450' : {
			'enabled':false,
			'online':false,
			'cid':'CS450',
			'sname':'Android Dev',
			'curriculum':'',
			'title1':'Android手机APP开发',
			'title2':'在Google商店发布你的手机App',
			'name':'Android手机APP开发:在Google商店发布你的手机App',
			'shortName':'Android手机APP开发',
			'imageUrl':'img/my/ios/bg-sm.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习流行的Java编程语言和Android手机App开发，在你的Android手机上运行自己的App',
			'tag':'移动互联网编程系列',
			'pathway':['mobile'],
			'detailsTitle':'查看详情',
			'detailsUrl':'mobileiosc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs451p' : {
			'enabled':false,
			'online':false,
			'cid':'CS451',
			'sname':'Android Dev Project',
			'curriculum':'',
			'title1':'Android手机APP开发',
			'title2':'项目开发',
			'name':'Android手机APP开发:项目开发',
			'shortName':'Android手机APP开发:项目开发',
			'imageUrl':'img/my/ios/bg-sm.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习流行的Java编程语言和Android手机App开发，在你的Android手机上运行自己的App（项目开发）',
			'tag':'移动互联网编程系列',
			'pathway':['mobile'],
			'detailsTitle':'查看详情',
			'detailsUrl':'mobileiosc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs460' : {
			'enabled':false,
			'online':false,
			'cid':'CS460',
			'sname':'Arduino Block',
			'curriculum':'',
			'title1':'电子工程师成长之路',
			'title2':'Arduino基础与图形化编程',
			'name':'电子工程师成长之路:Arduino基础与图形化编程',
			'shortName':'Arduino基础与图形化编程',
			'imageUrl':'img/my/arduino/arduino-bg-sm.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'制作智能电子系统，在硬件的世界学习软件，让你充分体验编程的强大',
			'tag':'移动互联网编程系列',
			'pathway':['hardware'],
			'detailsTitle':'查看详情',
			'detailsUrl':'arduinoc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs461' : {
			'enabled':true,
			'online':false,
			'cid':'CS461',
			'sname':'Arduino Pro',
			'curriculum':'',
			'title1':'电子工程师成长之路',
			'title2':'Arduino硬件系统编程',
			'name':'电子工程师成长之路:Arduino硬件系统编程',
			'shortName':'Arduino硬件系统编程',
			'imageUrl':'img/my/arduino/arduino-bg-sm.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'制作智能电子系统，在硬件的世界学习软件，让你充分体验编程的强大',
			'tag':'移动互联网编程系列',
			'pathway':['hardware'],
			'detailsTitle':'查看详情',
			'detailsUrl':'arduinoc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs470' : {
			'enabled':true,
			'online':false,
			'cid':'CS470',
			'sname':'Raspberry PI',
			'curriculum':'raspberrypi',
			'title1':'Raspberry PI智能物联网系统编程',
			'title2':'电子工程师成长之路',
			'name':'电子工程师成长之路:Raspberry PI智能物联网系统编程',
			'shortName':'Raspberry PI智能物联网系统编程',
			'imageUrl':'img/my/rpi/bg2.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'制作物联网电子系统，在硬件的世界学习软件，让你充分体验编程的强大',
			'tag':'移动互联网编程系列',
			'pathway':['hardware'],
			'detailsTitle':'查看详情',
			'detailsUrl':'rpic.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},		
		'cs471p' : {
			'enabled':false,
			'online':false,
			'cid':'CS471p',
			'sname':'Raspberry PI Project',
			'curriculum':'raspberrypi',
			'title1':'电子工程师成长之路',
			'title2':'项目实践',
			'name':'电子工程师成长之路:项目实践',
			'shortName':'电子工程师成长之路:项目实践',
			'imageUrl':'img/my/rpi/bg2.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'制作物联网电子系统，在硬件的世界学习软件，让你充分体验编程的强大(项目实践)',
			'tag':'移动互联网编程系列',
			'pathway':['hardware'],
			'detailsTitle':'查看详情',
			'detailsUrl':'rpic.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs480' : {
			'enabled':true,
			'online':false,
			'cid':'CS480',
			'sname':'Unreal 1',
			'curriculum':'',
			'title1':'Unreal游戏引擎专业游戏开发',
			'title2':'做你自己的Fortnite',
			'name':'Unreal游戏引擎专业游戏开发:做你自己的Fortnite',
			'shortName':'Unreal游戏引擎专业游戏开发',
			'imageUrl':'img/my/unreal/bg-sm.png',
			'gradeLevel':'L4应用主题编程',
			'text':'学习世界最流行的游戏开发引擎，让你在中学就可以挥洒创意，创作出你自己想玩的游戏。',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'unrealc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs481p' : {
			'enabled':false,
			'online':false,
			'cid':'CS481p',
			'sname':'Unreal 1 Project',
			'curriculum':'',
			'title1':'Unreal游戏引擎专业游戏开发',
			'title2':'项目实践I',
			'name':'Unreal游戏引擎专业游戏开发:项目实践I',
			'shortName':'Unreal游戏引擎专业游戏开发:项目实践I',
			'imageUrl':'img/my/unreal/bg-sm.png',
			'gradeLevel':'L4应用主题编程',
			'text':'学习世界最流行的游戏开发引擎，让你在中学就可以挥洒创意，创作出你自己想玩的游戏（项目实践）',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'unrealc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs482' : {
			'enabled':true,
			'online':false,
			'cid':'CS482',
			'sname':'Unreal 2',
			'curriculum':'',
			'title1':'Unreal高级开发与VR应用',
			'title2':'专业游戏开发工程师之路',
			'name':'Unreal高级开发与VR应用:专业游戏开发工程师之路',
			'shortName':'Unreal高级开发与VR应用',
			'imageUrl':'img/my/unreal/bg2-sm.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习Unreal的高级技术和技巧，做VR虚拟现实应用。',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'unreal2c.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs485' : {
			'enabled':true,
			'online':false,
			'cid':'CS485',
			'sname':'Maya 1',
			'curriculum':'',
			'title1':'Maya 3D动画设计与编程',
			'title2':'动画游戏开发设计师之路',
			'name':'Maya 3D动画设计与编程:动画游戏开发设计师之路',
			'shortName':'Maya 3D动画设计与编程',
			'imageUrl':'img/my/maya/bg.jpg',
			'gradeLevel':'L4应用主题编程',
			'text':'学习专业的3D建模与动画场景制作，艺术与编程的完美结合。',
			'tag':'游戏编程系列',
			'pathway':['game'],
			'detailsTitle':'查看详情',
			'detailsUrl':'mayac.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs490' : {
			'enabled':true,
			'online':false,
			'cid':'CS490',
			'sname':'Cyber Security',
			'curriculum':'',
			'title1':'计算机信息与网络安全',
			'title2':'做黑客的终结者',
			'name':'计算机信息与网络安全:做黑客的终结者',
			'shortName':'计算机信息与网络安全',
			'imageUrl':'img/my/security/bg-sm.jpeg',
			'gradeLevel':'L4应用主题编程',
			'text':'了解黑客的常见入侵原理，实验各种网络攻防技术，做合格的网络安全守护者。',
			'tag':'移动互联网编程系列',
			'pathway':['mobile'],
			'detailsTitle':'查看详情',
			'detailsUrl':'securityc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs501' : {
			'enabled':true,
			'online':false,
			'cid':'CS501',
			'sname':'USACO 1',
			'curriculum':'usaco50',
			'title1':'USACO信息学竞赛算法1',
			'title2':'信息学介绍与算法初步',
			'name':'USACO信息学竞赛算法1:信息学介绍与算法初步',
			'shortName':'USACO信息学竞赛算法1',
			'imageUrl':'img/my/ioi/bg-sm.jpeg',
			'gradeLevel':'L5竞技编程',
			'text':'熟悉USACO算法基础，解决、优化实际问题，备战USACO信息学竞赛',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'ioic.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},		
		'cs502' : {
			'enabled':true,
			'online':false,
			'cid':'CS502',
			'sname':'USACO 2',
			'curriculum':'usaco2',
			'title1':'USACO信息学竞赛算法2',
			'title2':'高级语言功能与算法强化',
			'name':'USACO信息学竞赛算法2:高级语言功能与算法介绍',
			'shortName':'USACO信息学竞赛算法2',
			'imageUrl':'img/my/ioi/bg-sm.jpeg',
			'gradeLevel':'L5竞技编程',
			'text':'学习高级算法，解决、优化实际问题，备战USACO信息学竞赛',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'ioic.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},		
		'cs505' : {
			'enabled':true,
			'online':false,
			'cid':'CS505',
			'sname':'USACO Bronze',
			'curriculum':'usaco-b',
			'title1':'USACO信息学竞赛挑战3',
			'title2':'备战计算机信息学奥赛',
			'name':'USACO信息学竞赛挑战3:备战计算机信息学奥赛',
			'shortName':'USACO信息学竞赛算法3',
			'imageUrl':'img/my/ioi/bg-sm.jpeg',
			'gradeLevel':'L5竞技编程',
			'text':'挑战青少年计算机的最高级别竞赛，在竞赛中锻炼自己的程序设计能力与技巧.',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'ioic.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},				
		'cs510' : {
			'enabled':true,
			'online':true,
			'cid':'CS510',
			'sname':'Java 1',
			'curriculum':'',
			'title1':'AP CS基础训练营',
			'title2':'Java编程入门及AP课程准备',
			'name':'AP CS基础训练营:Java编程入门及AP课程准备',
			'shortName':'Java编程入门及AP课程准备',
			'imageUrl':'img/my/coding-spacesm.jpg',
			'gradeLevel':'L5竞技编程',
			'text':'帮助零编程基础的高中同学准备AP CS课程和考试所需要的扎实的编程基本功',
			'tag':'AP CS编程系列',
			'pathway':['ap'],
			'detailsTitle':'查看详情',
			'detailsUrl':'apcs-cn.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs520' : {
			'enabled':true,
			'online':true,
			'cid':'CS520',
			'sname':'Java 3',
			'curriculum':'',
			'title1':'AP CS考试冲刺训练营',
			'title2':'AP CS备考强化训练',
			'name':'AP CS考试冲刺训练营:AP CS备考强化训练',
			'shortName':'AP CS备考强化训练',
			'imageUrl':'img/apcsprep/bg-sm.jpg',
			'gradeLevel':'L5竞技编程',
			'text':'为即将参加AP考试的同学复习课程重点，训练考试习题，强化考试所需要的编程基本功',
			'tag':'AP CS编程系列',
			'pathway':['ap'],
			'detailsTitle':'查看详情',
			'detailsUrl':'apcsprep-cn.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs521' : {
			'enabled':true,
			'online':true,
			'cid':'CS521',
			'sname':'Python Online',
			'curriculum':'',
			'title1':'Python编程网络直播',
			'title2':'学会Python，动手编写真正的计算机应用程序',
			'name':'名校申请背景强化课程:Python基础与应用程序开发',
			'shortName':'Python基础与应用程序开发',
			'imageUrl':'img/my/pythononline.png',
			'gradeLevel':'L5竞技编程',
			'text':'学习当今最流行的编程语言，开发任何你想制作的应用程序',
			'tag':'编程算法与AI系列',
			'pathway':['coding'],
			'detailsTitle':'查看详情',
			'detailsUrl':'pyonline-cn.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},		
		'cs531' : {
			'enabled':true,
			'online':true,
			'cid':'CS531',
			'sname':'App Inventor',
			'curriculum':'',
			'title1':'AP CSP手机APP编程训练营',
			'title2':'挑战最新的AP CS课程',
			'name':'AP CSP手机APP编程训练营:挑战最新的AP CS课程',
			'shortName':'AP CSP手机APP编程训练营',
			'imageUrl':'img/my/mobile-learn-0sm.jpg',
			'gradeLevel':'L5竞技编程',
			'text':'College Board的最新AP课程Computer Science Principles',
			'tag':'AP CS编程系列',
			'pathway':['ap'],
			'detailsTitle':'查看详情',
			'detailsUrl':'apcsp-cn.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs550' : {
			'enabled':false,
			'online':false,
			'cid':'CS550',
			'sname':'Lego Competition',
			'curriculum':'',
			'title1':'Lego机器人竞赛备战',
			'title2':'挑战真正的Lego竞赛',
			'name':'Lego机器人竞赛备战:挑战真正的Lego竞赛',
			'shortName':'Lego机器人竞赛备战',
			'imageUrl':'img/my/lego/lego2-bg-sm.jpg',
			'gradeLevel':'L5竞技编程',
			'text':'备战乐高机器人竞赛，竞赛中学习和提高',
			'tag':'机器人编程系列',
			'pathway':['robot'],
			'detailsTitle':'查看详情',
			'detailsUrl':'legoc2.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs560' : {
			'enabled':true,
			'online':true,
			'cid':'CS560',
			'sname':'App Development',
			'curriculum':'',
			'title1':'名校申请背景强化课程',
			'title2':'计算机编程系列手机App编程开发',
			'name':'名校申请背景强化课程:计算机编程系列手机App编程开发',
			'shortName':'计算机编程系列手机App编程开发',
			'imageUrl':'img/my/mobile-learn-6sm.jpg',
			'gradeLevel':'L5竞技编程',
			'text':'学习App编程，为AP CS课程、科学竞赛、课外项目和创业充实内容和经历',
			'tag':'名校申请背景强化系列',
			'pathway':['ce'],
			'detailsTitle':'查看详情',
			'detailsUrl':'ceappc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs561' : {
			'enabled':true,
			'online':false,
			'cid':'CS561',
			'sname':'Unity Advanced',
			'curriculum':'',
			'title1':'名校申请背景强化课程',
			'title2':'计算机编程系列Unity3D游戏开发',
			'name':'名校申请背景强化课程:计算机编程系列Unity3D游戏开发',
			'shortName':'计算机编程系列Unity3D游戏开发',
			'imageUrl':'img/my/unity3d/bg-2sm.jpg',
			'gradeLevel':'L5竞技编程',
			'text':'学习专业3D游戏开发，为AP CS课程、科学竞赛、课外项目和创业充实内容和经历',
			'tag':'名校申请背景强化系列',
			'pathway':['ce'],
			'detailsTitle':'查看详情',
			'detailsUrl':'ceunity3dc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs562' : {
			'enabled':true,
			'online':true,
			'cid':'CS562',
			'sname':'Python Advacned Project',
			'curriculum':'',
			'title1':'名校申请背景强化课程',
			'title2':'Python竞技编程与项目实践',
			'name':'名校申请背景强化课程:Python竞技编程与项目实践',
			'shortName':'Python竞技编程与项目实践',
			'imageUrl':'img/my/pythonmine/pyce-bg-sm.jpg',
			'gradeLevel':'L5竞技编程',
			'text':'学习Python算法，为AP CS课程、科学竞赛、课外项目和创业充实内容和经历',
			'tag':'名校申请背景强化系列',
			'pathway':['ce'],
			'detailsTitle':'查看详情',
			'detailsUrl':'cepythonc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs563' : {
			'enabled':true,
			'online':true,
			'cid':'CS563',
			'sname':'Advanced AI',
			'curriculum':'ai1',
			'title1':'名校申请背景强化课程',
			'title2':'人工智能基础与项目实践',
			'name':'名校申请背景强化课程:人工智能基础与项目实践',
			'shortName':'人工智能基础与项目实践',
			'imageUrl':'img/my/ceml/ai-sm.jpg',
			'gradeLevel':'L5竞技编程',
			'text':'学习Python算法，开发人工智能应用项目，为科学竞赛、课外项目和创业充实内容和经历',
			'tag':'名校申请背景强化系列',
			'pathway':['ce'],
			'detailsTitle':'查看详情',
			'detailsUrl':'cemlc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs564' : {
			'enabled':true,
			'online':false,
			'cid':'CS564',
			'sname':'Technovation',
			'curriculum':'',
			'title1':'名校申请背景强化课程',
			'title2':'Technovation编程竞技与创业竞赛',
			'name':'名校申请背景强化课程:Technovation编程竞技与创业竞赛',
			'shortName':'Technovation编程竞技与创业竞赛',
			'imageUrl':'img/my/cetech/te-bg.jpg',
			'gradeLevel':'L5竞技编程',
			'text':'学习APP编程开发，参加Technovation编程竞技与创业竞赛',
			'tag':'名校申请背景强化系列',
			'pathway':['ce'],
			'detailsTitle':'查看详情',
			'detailsUrl':'cetechc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs565' : {
			'enabled':true,
			'online':true,
			'cid':'CS565',
			'sname':'Fluuter',
			'curriculum':'flutter',
			'title1':'名校申请背景强化课程',
			'title2':'Flutter跨平台手机App开发',
			'name':'Flutter跨平台手机App开发:同时发布Android和iOS',
			'shortName':'Flutter跨平台手机App开发',
			'imageUrl':'img/my/flutter/flutter.png',
			'gradeLevel':'L5竞技编程',
			'text':'学习最新跨平台手机开发，实现Android和iOS的同步支持',
			'tag':'名校申请背景强化系列',
			'pathway':['ce'],
			'detailsTitle':'查看详情',
			'detailsUrl':'flutterc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs570' : {
			'enabled':true,
			'online':false,
			'cid':'CS570',
			'sname':'Startup',
			'curriculum':'',
			'title1':'名校申请背景强化课程',
			'title2':'青少年科技创业项目',
			'name':'名校申请背景强化课程:青少年科技创业项目',
			'shortName':'青少年科技创业项目',
			'imageUrl':'img/my/cestartup/bg-sm.png',
			'gradeLevel':'L5竞技编程',
			'text':'编程创新，学以致用，解决实际问题，做自己的创业公司',
			'tag':'名校申请背景强化系列',
			'pathway':['ce'],
			'detailsTitle':'查看详情',
			'detailsUrl':'cestartupc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		},
		'cs571' : {
			'enabled':true,
			'online':false,
			'cid':'CS571',
			'sname':'Science Fair',
			'curriculum':'',
			'title1':'Science Fair科学竞赛强化',
			'title2':'编程助理科学竞赛',
			'name':'Science Fair科学竞赛强化:编程助理科学竞赛',
			'shortName':'Science Fair科学竞赛强化',
			'imageUrl':'img/my/cestartup/bg-sm.png',
			'gradeLevel':'L5竞技编程',
			'text':'编程创新，学以致用，解决实际问题，在科学竞赛脱颖而出',
			'tag':'名校申请背景强化系列',
			'pathway':['ce'],
			'detailsTitle':'查看详情',
			'detailsUrl':'sciencefairc.html',
			'locations':'选择地点',
			'registerUrl':'corecn.html#allCourses',
			'registerTitle':'我要注册',
			'registerForm':'https://jinshuju.net/f/0KnUba'
		}
	}
}


var templist = []
var copy = {}
Object.keys(coursedb.cn).forEach(key=>{
	if (coursedb.cn[key].enabled===true){
		delete coursedb.cn[key].cid;
		copy = coursedb.cn[key]
		key.toLowerCase();
        copy["courseCode"] = key;
		templist.push(copy)
	}
	}
)

console.log(JSON.stringify(templist))
