var courseList = {
	'cn': [
		{
			'name':'Minecraft创新编程与实践:用最流行的游戏学编程',
			'imageUrl':'img/my/minecode/minecodebgsm.jpg',
			'gradeLevel':'2-6年级',
			'text':'在Minecraft我的世界游戏中学习编程将是孩子们理想的学习体验',
			'detailsTitle':'查看详情',
			'detailsUrl':'minecodec.html',
			'registerTitle':'我要注册',
			'registerUrl':'minecodec.html'
		},
		{
			'name':'和SPRK机器人一起学习编程:带领你的机器人完成挑战',
			'imageUrl':'img/my/sprk-learn-5sm.jpg',
			'gradeLevel':'2-6年级',
			'text':'学习如何通过编程控制SPRK机器人，打开神奇计算机编程世界的大门',
			'detailsTitle':'查看详情',
			'detailsUrl':'sprkc.html',
			'registerTitle':'我要注册',
			'registerUrl':'sprkc.html'
		},
		{
			'name':'MIT Scratch创新编程与实践:做你自己的游戏、动画、多媒体',
			'imageUrl':'img/my/scratch/scratchbg.png',
			'gradeLevel':'2-6年级',
			'text':'学Scratch编程，发挥你的创造力，和来自世界各地的小程序员分享你的作品',
			'detailsTitle':'查看详情',
			'detailsUrl':'scratchc.html',
			'registerTitle':'我要注册',
			'registerUrl':'scratchc.html'
		},
		{
			'name':'Roblox游戏开发与发布:游戏创业学编程',
			'imageUrl':'img/my/roblox1/bg-sm.jpg',
			'gradeLevel':'3-6年级',
			'text':'学习开发风靡全球的Roblox，发布你自己的游戏，创业编程两不误',
			'detailsTitle':'查看详情',
			'detailsUrl':'roblox1c.html',
			'registerTitle':'我要注册',
			'registerUrl':'roblox1c.html'
		},
		{
			'name':'Lego MindStorms机器人编程挑战:挑战不可能的任务',
			'imageUrl':'img/my/lego/lego-bg-sm.jpg',
			'gradeLevel':'4-8年级',
			'text':'在控制机器人挑战自己过程中学习编程,将是你从未尝试过的学习体验',
			'detailsTitle':'查看详情',
			'detailsUrl':'legoc.html',
			'registerTitle':'我要注册',
			'registerUrl':'legoc.html'
		},
		{
			'name':'电子工程师成长之路:Arduino硬件系统编程',
			'imageUrl':'img/my/arduino/arduino-bg-sm.jpg',
			'gradeLevel':'6-12年级',
			'text':'制作智能电子系统，在硬件的世界学习软件，让你充分体验编程的强大',
			'detailsTitle':'查看详情',
			'detailsUrl':'arduinoc.html',
			'registerTitle':'我要注册',
			'registerUrl':'arduinoc.html'
		},
		{
			'name':'Roblox游戏开发进阶与Lua编程:游戏创业学编程',
			'imageUrl':'img/my/roblox1/bg2-sm.jpg',
			'gradeLevel':'6-12年级',
			'text':'学习开发风靡全球的Roblox，发布你自己的游戏，创业编程两不误',
			'detailsTitle':'查看详情',
			'detailsUrl':'roblox2c.html',
			'registerTitle':'我要注册',
			'registerUrl':'roblox2c.html'
		},
		{
			'name':'Unity3D游戏开发体验:从游戏玩家到游戏开发员',
			'imageUrl':'img/my/unity3d/unity3d-1sm.jpg',
			'gradeLevel':'7-12年级',
			'text':'学习世界最流行的游戏开发引擎，让你在中学就可以挥洒创意，创作出你自己想玩的游戏。',
			'detailsTitle':'查看详情',
			'detailsUrl':'unity3dc.html',
			'registerTitle':'我要注册',
			'registerUrl':'unity3dc.html'
		},
		{
			'name':'Python编程初步：学做Minecraft游戏开发员',
			'imageUrl':'img/my/pythonmine/pyminebghp.jpg',
			'gradeLevel':'7-12年级',
			'text':'在世界最流行的游戏中学习世界最流行的编程语言Python',
			'detailsTitle':'查看详情',
			'detailsUrl':'python-minecraftc.html',
			'registerTitle':'我要注册',
			'registerUrl':'python-minecraftc.html'
		},
		{
			'name':'MIT手机APP发明家:动手编写自己的APP做小小创业者',
			'imageUrl':'img/my/app-dev-2sm.jpg',
			'gradeLevel':'7-12年级',
			'text':'厌倦了每天玩自己的手机APP？那就学习如动手编程制作自己的手机APP，做下一个年轻的创业者',
			'detailsTitle':'查看详情',
			'detailsUrl':'mobilec.html',
			'registerTitle':'我要注册',
			'registerUrl':'mobilec.html'
		},
		{
			'name':'Python编程实践:动手编写真正的计算机应用程序',
			'imageUrl':'img/my/python-learn-3.jpg',
			'gradeLevel':'7-12年级',
			'text':'学习当今最流行的编程语言，开发任何你想制作的应用程序',
			'detailsTitle':'查看详情',
			'detailsUrl':'pythonc.html',
			'registerTitle':'我要注册',
			'registerUrl':'pythonc.html'
		},
		{
			'name':'AP CS基础训练营:Java编程入门及AP课程准备',
			'imageUrl':'img/my/coding-spacesm.jpg',
			'gradeLevel':'8-12年级',
			'text':'帮助零编程基础的高中同学准备AP CS课程和考试所需要的扎实的编程基本功',
			'detailsTitle':'查看详情',
			'detailsUrl':'apcs-cn.html',
			'registerTitle':'我要注册',
			'registerUrl':'apcs-cn.html'
		},
		{
			'name':'AP CS考试冲刺训练营:AP CS备考强化训练',
			'imageUrl':'img/apcsprep/bg-sm.jpg',
			'gradeLevel':'9-12年级',
			'text':'为即将参加AP考试的同学复习课程重点，训练考试习题，强化考试所需要的编程基本功',
			'detailsTitle':'查看详情',
			'detailsUrl':'apcsprep-cn.html',
			'registerTitle':'我要注册',
			'registerUrl':'apcsprep-cn.html'
		},
		{
			'name':'AP CSP手机APP编程训练营:挑战最新的AP CS课程',
			'imageUrl':'img/my/mobile-learn-0sm.jpg',
			'gradeLevel':'8-12年级',
			'text':'College Board的最新AP课程Computer Science Principles',
			'detailsTitle':'查看详情',
			'detailsUrl':'apcsp-cn.html',
			'registerTitle':'我要注册',
			'registerUrl':'apcsp-cn.html'
		},
		{
			'name':'名校申请背景强化课程：计算机编程系列手机App编程开发',
			'imageUrl':'img/my/mobile-learn-6sm.jpg',
			'gradeLevel':'9-12年级',
			'text':'学习App编程，为AP CS课程、科学竞赛、课外项目和创业充实内容和经历',
			'detailsTitle':'查看详情',
			'detailsUrl':'ceappc.html',
			'registerTitle':'我要注册',
			'registerUrl':'ceapp.html'
		},
		{
			'name':'名校申请背景强化课程：计算机编程系列Unity3D游戏开发',
			'imageUrl':'img/my/unity3d/bg-2sm.jpg',
			'gradeLevel':'9-12年级',
			'text':'学习专业3D游戏开发，为AP CS课程、科学竞赛、课外项目和创业充实内容和经历',
			'detailsTitle':'查看详情',
			'detailsUrl':'ceunity3dc.html',
			'registerTitle':'我要注册',
			'registerUrl':'ceunity3dc.html'
		},
		{
			'name':'名校申请背景强化课程：Python竞技编程与项目实践',
			'imageUrl':'img/my/pythonmine/pyce-bg-sm.jpg',
			'gradeLevel':'9-12年级',
			'text':'学习Python算法，为AP CS课程、科学竞赛、课外项目和创业充实内容和经历',
			'detailsTitle':'查看详情',
			'detailsUrl':'cepythonc.html',
			'registerTitle':'我要注册',
			'registerUrl':'cepythonc.html'
		},
	]
}

angular.module('v3App', [])
  .config(function($sceProvider) {
    $sceProvider.enabled(false);
  })
  .controller('CourseListController', function($scope) {
    $scope.courseList = courseList.cn;
  });
