var coursedb = {
	'cn': {
    "cs130": {
     "enabled": true,
     "name": "Minecraft创新编程与实践:用最流行的游戏学编程",
     "imageUrl": "img/my/minecode/minecodebgsm.jpg",
     "gradeLevel": "L1图形化编程",
     "text": "在Minecraft我的世界游戏中学习编程将是孩子们理想的学习体验",
     "tag": "游戏编程系列",
     "courseCode": "cs130",
     "suggestedCourses": [
      "cs220"
     ],
     "introduction": "Minecraft MakeCode编程是L1级别最受大家欢迎的题目，课程主要通过微软的MakeCode开发平台，学习如何通过图形化编程，进行Minecraft游戏的开发与制作。同学可以通过编程动手实现自己在Minecraft游戏里面所没有的功能和想法，为开发发布自己的游戏创造了无限的可能。",
     "completion": "Minecraft MakeCode编程是L1级别最受大家欢迎的题目，通过课程的学习，同学已经掌握了微软的MakeCode开发平台，熟悉如何通过图形化编程，进行Minecraft游戏的开发与制作。同学通过编程动手实现了自己在Minecraft游戏里面所没有的功能和想法，并且发布了自己的游戏程序。",
     "detailsUrl": "minecodec.html",
     "id": "5f1f5b2457e17945692b2717",
     "online": false,
     "sname": "Minecraft MakeCode",
     "curriculum": "minecraft1",
     "title1": "Minecraft创新编程与实践",
     "title2": "用最流行的游戏学编程",
     "shortName": "Minecraft创新编程与实践",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs110": {
     "enabled": true,
     "name": "Minecraft世界开发与编程:学习实践AI基础",
     "imageUrl": "img/my/minecode/mcai.jpg",
     "gradeLevel": "L1图形化编程",
     "text": "在Minecraft游戏中学习AI在游戏中的初步应用，学习开发第一个人工智能程序",
     "tag": "游戏编程系列",
     "courseCode": "cs110",
     "suggestedCourses": [],
     "detailsUrl": "mcbuildc.html",
     "id": "5f1f5b2457e17945692b2718",
     "online": false,
     "sname": "Minecraft AI",
     "curriculum": "minecraft1",
     "title1": "少儿AI编程Minecraft",
     "title2": "图形化编程入基础",
     "shortName": "少儿AI编程Minecraft",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corncn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs200": {
     "enabled": true,
     "name": "Javascript编程初步: Minecraft MakeCode编程",
     "imageUrl": "img/my/minecraftbasic/bg2-sm.jpg",
     "gradeLevel": "L2简洁代码编程",
     "text": "在微软的MakeCode平台中学习Javscript的基础，开始代码编程之路",
     "tag": "游戏编程系列",
     "courseCode": "cs200",
     "suggestedCourses": [],
     "detailsUrl": "mcbuild2c.html",
     "id": "5f1f5b2457e17945692b2719",
     "online": false,
     "sname": "Minecraft JavaScript",
     "curriculum": "minecraft1",
     "title1": "Javascript编程初步",
     "title2": "Minecraft MakeCode编程",
     "shortName": "Javascript编程初步MakeCode",
     "pathway": [
      "coding",
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs210": {
     "enabled": true,
     "name": "Javascript编程进阶: MicroBit电子电路编程",
     "imageUrl": "img/my/microbit/bg.jpg",
     "gradeLevel": "L2简洁代码编程",
     "text": "学习微软最新的MicroBit编程，控制电子小元件，发挥你的创造力，体验编程的神奇",
     "tag": "游戏编程系列",
     "courseCode": "cs210",
     "suggestedCourses": [],
     "detailsUrl": "",
     "id": "5f1f5b2457e17945692b271a",
     "online": false,
     "sname": "MicroBit",
     "curriculum": "",
     "title1": "Javascript编程进阶",
     "title2": "MicroBit电子电路编程",
     "shortName": "Javascript编程进阶MicroBit",
     "pathway": [
      "hardware"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "microbit-cn.html",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs220": {
     "enabled": true,
     "name": "Roblox游戏开发与Lua编程:开发游戏学Lua编程",
     "imageUrl": "img/my/roblox1/bg-sm.jpg",
     "gradeLevel": "L2简洁代码编程",
     "text": "学习开发风靡全球的Roblox，发布你自己的游戏，创业编程两不误",
     "tag": "游戏编程系列",
     "courseCode": "cs220",
     "suggestedCourses": [
      "cs230"
     ],
     "introduction": "Roblox 1作为L2级别的核心课程，主要的目标是带领同学开始编写相对简洁的代码程序，而不再使用初级的图形化编程。课程的要求同学掌握基本Lua程序代码的语法和控制流程，并且能够完成了一个初步的Roblox的游戏项目，为下一阶段的高级Lua编程打下良好的基础。",
     "completion": "Roblox 1作为L2级别的核心课程，主要的目标是带领同学开始编写相对简洁的代码程序，而不再使用初级的图形化编程。通过本节课的完成，同学已经掌握了基本Lua程序代码的语法和控制流程，并且完成了一个初步的Roblox的游戏项目，为下一阶段的高级Lua编程打下良好的基础。",
     "detailsUrl": "roblox1c.html",
     "id": "5f1f5b2457e17945692b271b",
     "online": false,
     "sname": "Roblox 1",
     "curriculum": "roblox1",
     "title1": "Roblox游戏开发与Lua编程",
     "title2": "游戏创业学Lua编程",
     "shortName": "Roblox游戏开发与Lua编程",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba",
     "nextCourseId": "CS230"
    },
    "cs101": {
     "enabled": true,
     "name": "Minecraft世界开发与编程:图形化编程入基础",
     "imageUrl": "img/my/minecraftbasic/bg-sm.jpg",
     "gradeLevel": "L1图形化编程",
     "text": "在Minecraft游戏中学习3D建模、控制指令与图形编程初步",
     "tag": "游戏编程系列",
     "courseCode": "cs101",
     "suggestedCourses": [],
     "detailsUrl": "mcbuildc.html",
     "englishDetailsUrl": "mcbuild.html",
     "id": "5f1f5b2457e17945692b271c",
     "online": false,
     "sname": "Minecraft World Building",
     "curriculum": "minecraft1",
     "title1": "Minecraft世界开发与编程",
     "title2": "图形化编程入基础",
     "shortName": "Minecraft世界开发与编程",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corncn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs240": {
     "enabled": true,
     "name": "人工智能初步与Lua实践:AI与智能游戏编程",
     "imageUrl": "img/my/roblox3/bg2-sm.jpg",
     "gradeLevel": "L3代码编程",
     "text": "在Roblox平台开发智能游戏AI，开启AI编程学习的第一步",
     "tag": "游戏编程系列",
     "courseCode": "cs240",
     "suggestedCourses": [],
     "introduction": "从Roblox 3开始，同学已经计入到L3级别的编程课程，该级别要求同学完全专注于代码的编程和算法设计与实现。通过本节课的完成，同学学习了Lua代码实现初步的AI功能与逻辑，并且完成了一个AI游戏算法并植入到了自己的游戏项目项目中去，对AI世界有了初步的体验。",
     "detailsUrl": "roblox3c.html",
     "id": "5f1f5b2457e17945692b271d",
     "online": false,
     "sname": "Roblox 3 Game AI",
     "curriculum": "",
     "title1": "人工智能初步与Lua实践",
     "title2": "AI与智能游戏编程",
     "shortName": "人工智能初步与Lua实践",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba",
     "nextCourseId": "CS300"
    },
    "cs230": {
     "enabled": true,
     "name": "Roblox游戏开发与Lua编程进阶:游戏创业学编程",
     "imageUrl": "img/my/roblox1/bg2-sm.jpg",
     "gradeLevel": "L2简洁代码编程",
     "text": "学习开发风靡全球的Roblox，发布你自己的游戏，创业编程两不误",
     "tag": "游戏编程系列",
     "courseCode": "cs230",
     "suggestedCourses": [],
     "introduction": "Roblox 2是L2级别的核心课程，主要的目标是让同学使用Lua更多的编写简洁的代码程序，尝试设计程序算法，并且可以独立的构思功能并融入到项目中去。本节课同学需要完成所有常用的Lua编程语言的功能特点，并且完成一个可以参赛的综合的Roblox的游戏项目，为下一阶段L3的编程学习做好准备。",
     "completion": "Roblox 2是L2级别的核心课程，主要的目标是让同学使用Lua更多的编写简洁的代码程序，尝试设计程序算法，并且可以独立的构思功能并融入到项目中去。通过本节课的完成，同学已经完成所有常用的Lua编程语言的功能特点，并且完成了一个可以参赛的综合的Roblox的游戏项目，为下一阶段L3的编程学习做好了准备。",
     "detailsUrl": "roblox2c.html",
     "id": "5f1f5b2457e17945692b271e",
     "online": false,
     "sname": "Roblox 2",
     "curriculum": "roblox2",
     "title1": "Roblox游戏开发与Lua编程进阶",
     "title2": "游戏创业学编程",
     "shortName": "Roblox游戏开发与Lua编程进阶",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba",
     "nextCourseId": "CS240"
    },
    "cs320": {
     "enabled": true,
     "name": "数据结构与算法:深入了解计算机数据结构与算法原理",
     "imageUrl": "img/my/python2.jpg",
     "gradeLevel": "L3代码编程",
     "text": "学习编程语言Python的高级算法，解决、优化实际问题",
     "tag": "编程算法与AI系列",
     "courseCode": "cs320",
     "suggestedCourses": [],
     "detailsUrl": "pythonc2.html",
     "id": "5f1f5b2457e17945692b271f",
     "online": false,
     "sname": "Python 3",
     "curriculum": "",
     "title1": "数据结构与算法",
     "title2": "数据结构与算法介绍",
     "shortName": "数据结构与算法",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs310": {
     "enabled": true,
     "name": "Python编程高阶:动手编写真正的计算机应用程序",
     "imageUrl": "img/my/python-learn-3.jpg",
     "gradeLevel": "L3代码编程",
     "text": "学习当今最流行的编程语言，开发任何你想制作的应用程序",
     "tag": "编程算法与AI系列",
     "courseCode": "cs310",
     "suggestedCourses": [
      "cs410",
      "cs430"
     ],
     "introduction": "Python 2作为L3级别的高级核心课程，主要的目标是带领同学使用Python进行程序算法的设计与实现，并且学习高级数据结构的知识。通过课程的完成，试同学可以掌握Python的数据结构与算法，并且完成一个综合的Python项目，为下一阶段L4级别的主题应用编程打下良好的基础。",
     "completion": "Python 2作为L3级别的核心课程，主要的目标是带领同学使用Python进行基本程序算法的设计与实现，并且学习高级数据结构的知识。通过课程的完成，同学已经掌握了Python的数据结构与算法，并且完成了一个综合的Python项目，为下一阶段L4级别的主题应用编程打下了良好的基础。",
     "detailsUrl": "pythonc.html",
     "id": "5f1f5b2457e17945692b2720",
     "online": false,
     "sname": "Python 2",
     "curriculum": "python2",
     "title1": "Python编程高阶",
     "title2": "动手编写真正的计算机应用程序",
     "shortName": "Python编程高阶",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba",
     "nextCourseId": "cs430"
    },
    "cs160": {
     "enabled": true,
     "name": "MIT Scratch创新编程与实践:做你自己的游戏、动画、多媒体",
     "imageUrl": "img/my/scratch/scratchbg.png",
     "gradeLevel": "L1图形化编程",
     "text": "学Scratch编程，发挥你的创造力，和来自世界各地的小程序员分享你的作品",
     "tag": "游戏编程系列",
     "courseCode": "cs160",
     "suggestedCourses": [],
     "introduction": "Scratch是L1图形化编程的核心课程，通过学习MIT研发的少儿编程平台，能够让同学们很快的理解编程的概念与基本语法，并且能够过从第一节课就开始制作趣味的编程应用。使用 Scratch，你可以编写属于你自己的互动媒体，比如故事、游戏、动画，然后你可以将你的创意分享给全世界。 ",
     "completion": "Scratch是L1图形化编程的核心课程，通过学习MIT研发的少儿编程平台，同学已经很好掌握理解了编程的概念与基本语法，并且能够过从第一节课就开始制作趣味的编程应用。过去一段时间，同学使用 Scratch，已经编写出了属于自己的互动媒体，比如故事、游戏、动画，并且把自己的创意分享到MIT的项目平台中。",
     "detailsUrl": "scratchc.html",
     "id": "5f1f5b2457e17945692b2721",
     "online": false,
     "sname": "Scratch 1",
     "curriculum": "",
     "title1": "MIT Scratch创新编程与实践",
     "title2": "做你自己的游戏、动画、多媒体",
     "shortName": "MIT Scratch创新编程与实践",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs150": {
     "enabled": true,
     "name": "Lego MindStorms机器人编程挑战:挑战不可能的任务",
     "imageUrl": "img/my/lego/lego-bg-sm.jpg",
     "gradeLevel": "L1图形化编程",
     "text": "在控制机器人挑战自己过程中学习编程,将是你从未尝试过的学习体验",
     "tag": "机器人编程系列",
     "courseCode": "cs150",
     "suggestedCourses": [],
     "detailsUrl": "legoc.html",
     "id": "5f1f5b2457e17945692b2722",
     "online": false,
     "sname": "Lego Robotics 1",
     "curriculum": "",
     "title1": "Lego MindStorms机器人编程挑战",
     "title2": "挑战不可能的任务",
     "shortName": "Lego机器人编程挑战",
     "pathway": [
      "robot"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs140": {
     "enabled": true,
     "name": "和SPRK机器人一起学习编程:带领你的机器人完成挑战",
     "imageUrl": "img/my/sprk-learn-5sm.jpg",
     "gradeLevel": "L1图形化编程",
     "text": "学习如何通过编程控制SPRK机器人，打开神奇计算机编程世界的大门",
     "tag": "机器人编程系列",
     "courseCode": "cs140",
     "suggestedCourses": [],
     "detailsUrl": "sprkc.html",
     "id": "5f1f5b2457e17945692b2723",
     "online": false,
     "sname": "SPRK Robotics",
     "curriculum": "",
     "title1": "和SPRK机器人一起学习编程",
     "title2": "带领你的机器人完成挑战",
     "shortName": "和SPRK机器人一起学习编程",
     "pathway": [
      "robot"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs350": {
     "enabled": true,
     "name": "Lego机器人进阶之Java编程:用真正的编程控制机器人",
     "imageUrl": "img/my/lego/lego2-bg-sm.jpg",
     "gradeLevel": "L3代码编程",
     "text": "在控制机器人挑战自己过程中学习Java编程,编程变得更加丰富多彩",
     "tag": "机器人编程系列",
     "courseCode": "cs350",
     "suggestedCourses": [],
     "detailsUrl": "legoc2.html",
     "id": "5f1f5b2457e17945692b2724",
     "online": false,
     "sname": "Lego Robotics 2",
     "curriculum": "",
     "title1": "Lego机器人进阶之Java编程",
     "title2": "用真正的编程控制机器人",
     "shortName": "Lego机器人进阶之Java编程",
     "pathway": [
      "robot"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs400": {
     "enabled": true,
     "name": "MIT手机APP发明家:动手编写自己的APP做小小创业者",
     "imageUrl": "img/my/app-dev-2sm.jpg",
     "gradeLevel": "L4应用主题编程",
     "text": "厌倦了每天玩自己的手机APP？那就学习动手编程制作自己的手机APP，做下一个年轻的创业者",
     "tag": "移动互联网编程系列",
     "courseCode": "cs400",
     "suggestedCourses": [],
     "detailsUrl": "mobilec.html",
     "id": "5f1f5b2457e17945692b2725",
     "online": false,
     "sname": "Thukable",
     "curriculum": "",
     "title1": "MIT手机APP发明家",
     "title2": "动手编写自己的APP做小小创业者",
     "shortName": "MIT手机APP发明家",
     "pathway": [
      "mobile"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs300": {
     "enabled": true,
     "name": "Python编程初步:学做Minecraft游戏开发员",
     "imageUrl": "img/my/pythonmine/pyminebghp.jpg",
     "gradeLevel": "L3代码编程",
     "text": "在世界最流行的游戏中学习世界最流行的编程语言Python",
     "tag": "编程算法与AI系列",
     "courseCode": "cs300",
     "suggestedCourses": [
      "cs310"
     ],
     "introduction": "Python 1作为L3级别的第一个核心课程，主要的目标是教授同学使用Python的基本语法与指令，并且能够完成基础的应用程序的开发。通过课程的完成，同学可以掌握Python的基础知识，并且完成一个基础的Python项目，为下一阶段的Python进阶编程打下良好的基础。",
     "completion": "Python 1作为L3级别的第一个核心课程，主要的目标是教授同学使用Python的基本语法与指令，并且能够完成基础的应用程序的开发。通过课程的完成，同学已经掌握了Python的基础知识，并且完成了一个基础的Python项目，为下一阶段的Python进阶编程打下了良好的基础。",
     "detailsUrl": "python-minecraftc.html",
     "id": "5f1f5b2457e17945692b2726",
     "online": false,
     "sname": "Python 1",
     "curriculum": "python1",
     "title1": "Python编程初步",
     "title2": "学做Minecraft游戏开发员",
     "shortName": "Python编程初步",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba",
     "nextCourseId": "cs310"
    },
    "cs170": {
     "enabled": true,
     "name": "MIT Scratch编程高阶:做你自己的游戏、动画、多媒体",
     "imageUrl": "img/my/scratch/scratch2.jpg",
     "gradeLevel": "L1图形化编程",
     "text": "学Scratch编程，发挥你的创造力，和来自世界各地的小程序员分享你的作品",
     "tag": "游戏编程系列",
     "courseCode": "cs170",
     "suggestedCourses": [],
     "introduction": "Scratch的进阶编程属于图形化编程的后一阶段，是往简洁代码与代码编程过度的最后一个课程。该课程强调学生的综合应用能力培养，不但要求同学完成Scratch高级知识点，更重要的目标是培养同学设计编程算法和系统应用的能力北京，能够完全把自己的idea独立动手实现。",
     "completion": "Scratch的进阶编程属于图形化编程的后一阶段，是往简洁代码与代码编程过度的最后一个课程。通过课程学习，同学不但完成Scratch高级知识点，更重要的是培养了同学设计编程算法和系统应用的能力北京，使同学能够完全把自己的idea独立动手实现，为代码编程打下基础。",
     "detailsUrl": "scratch2c.html",
     "id": "5f1f5b2457e17945692b2727",
     "online": false,
     "sname": "Scratch 2",
     "curriculum": "",
     "title1": "MIT Scratch编程高阶",
     "title2": "做你自己的游戏、动画、多媒体",
     "shortName": "MIT Scratch编程高阶",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs410": {
     "enabled": true,
     "name": "Unity3D游戏开发体验:从游戏玩家到游戏开发员",
     "imageUrl": "img/my/unity3d/unity3d-1sm.jpg",
     "gradeLevel": "L4应用主题编程",
     "text": "学习世界最流行的游戏开发引擎，让你在中学就可以挥洒创意，创作出你自己想玩的游戏。",
     "tag": "游戏编程系列",
     "courseCode": "cs410",
     "suggestedCourses": [
      "cs420"
     ],
     "introduction": "Unity3D游戏开发是L4级别游戏动画方向的核心课程，主要的目标是让同学开始学习C#高级编程语言，并且使用专业的游戏引擎，开发可以发布的2D或3D的动画和游戏。该课程可以很好的将L3级别中学到的编程基础与算法应用到实际的项目中去。本节课同学需要完成基础的Unity3D开发功能库，掌握C#编程语言，以及完成一个可以参赛的综合的游戏项目。",
     "completion": "Unity3D游戏开发是L4级别游戏动画方向的核心课程，主要的目标是让同学学习C#高级编程语言，并且使用专业的游戏引擎，开发可以发布的2D或3D的动画和游戏。通过学习该课程，同学已经掌握了基础的Unity3D开发功能库和C#编程语言，很好的将编程基础与编程算法应用到实际的项目中去，并且最终完成一个了可以参赛的综合的游戏项目。",
     "detailsUrl": "unity3dc.html",
     "id": "5f1f5b2457e17945692b2728",
     "online": false,
     "sname": "Unity 1",
     "curriculum": "unity1",
     "title1": "Unity3D游戏开发体验",
     "title2": "从游戏玩家到游戏开发员",
     "shortName": "Unity3D游戏开发体验",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs425": {
     "enabled": true,
     "name": "人工智能与游戏AI设计:专业游戏游戏开发员养成之路",
     "imageUrl": "img/my/unity3d/gameai1.jpg",
     "gradeLevel": "L4应用主题编程",
     "text": "学习游戏开发引擎的高级技巧和知识，创作专业游戏作品。",
     "tag": "游戏编程系列",
     "courseCode": "cs425",
     "suggestedCourses": [],
     "introduction": "人工智能与游戏AI设计课程属于游戏编程和人工智能应用的高阶课程，主要是将AI算法应用在游戏开发当中，在完善自己游戏的同时学习并应用人工智能知识",
     "detailsUrl": "unity3d2c.html",
     "id": "5f1f5b2457e17945692b2729",
     "online": false,
     "sname": "Game AI",
     "curriculum": "",
     "title1": "人工智能与游戏AI设计",
     "title2": "专业游戏游戏开发员养成之路",
     "shortName": "人工智能与游戏AI设计",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs420": {
     "enabled": true,
     "name": "Unity3D游戏开发进阶:专业游戏游戏开发员养成之路",
     "imageUrl": "img/my/unity3d/bg-3sm.jpg",
     "gradeLevel": "L4应用主题编程",
     "text": "学习游戏开发引擎的高级技巧和知识，创作专业游戏作品。",
     "tag": "游戏编程系列",
     "courseCode": "cs420",
     "suggestedCourses": [],
     "introduction": "Unity 2是L4级别游戏开发主题的进阶课程，在同学掌握Unity 1的基础上，课程开始更加着重C#编码在游戏开发中的比重，进一步让同学掌握游戏算法的设计与实现，锻炼同学独立开发游戏动画的能力，以及准备更具深度的游戏项目作品，为专业游戏发布做好准备。",
     "completion": "Unity 2是L4级别游戏开发主题的进阶课程，在同学掌握Unity 1的基础上，课程开始更加着重C#编码在游戏开发中的比重。通过课程的学习，同学进一步掌握了游戏算法的设计与实现，锻炼了同学独立开发游戏动画的能力，同学也完成了更具深度的游戏项目作品，为专业游戏发布做好了准备。",
     "detailsUrl": "unity3d2c.html",
     "id": "5f1f5b2457e17945692b272a",
     "online": false,
     "sname": "Unity 2",
     "curriculum": "unity2",
     "title1": "Unity3D游戏开发进阶",
     "title2": "专业游戏游戏开发员养成之路",
     "shortName": "Unity3D游戏开发进阶",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs436": {
     "enabled": true,
     "name": "网络爬虫与数据分析:数据工程的起点",
     "imageUrl": "img/my/cewcr/bg-big.jpg",
     "gradeLevel": "L4应用主题编程",
     "text": "学习爬虫算法，获取前沿数据",
     "tag": "编程算法与AI系列",
     "courseCode": "cs436",
     "suggestedCourses": [],
     "introduction": "该课程作为L4的应用主题课程，为学生介绍网络爬虫与数据分析应用程序开发。课程学习Python数据爬虫核心，掌握各种爬虫应用场景，学习数据驱动的Web应用开发原理，并且独立设计并完成一个自己的数据监控与分析Web应用。课程结束每个学生会完成，并发布自己的数据监控网站，为高中科学竞赛、课外项目和创业充实内容和经历。",
     "completion": "作为L4的应用主题课程，同学已经掌握Python数据爬虫核心，各种爬虫应用场景，以及数据驱动的Web应用开发原理，同学也独立设计并完成一个自己的数据监控与分析，并发布了自己的数据监控网站。",
     "detailsUrl": "webscraping.html",
     "id": "5f1f5b2457e17945692b272b",
     "online": false,
     "sname": "Web Scraping",
     "curriculum": "webcr",
     "title1": "网络爬虫与数据分析",
     "title2": "做未来的数据工程师",
     "shortName": "网络爬虫与数据分析",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "webscrapingc.html",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs435": {
     "enabled": true,
     "name": "AI高阶编程:探索深度学习与区块链技术",
     "imageUrl": "img/my/ai2/ai2-bg.png",
     "gradeLevel": "L4应用主题编程",
     "text": "学习人工智能的高级知识与应用了解最前沿的技术革新",
     "tag": "编程算法与AI系列",
     "courseCode": "cs435",
     "suggestedCourses": [],
     "introduction": "AI 2是AI的进阶课程，主要目标是让同学从普通机器学习，过度到深度学习与神经网络的高级题目与应用中，并且掌握如何使用深度学习的功能库来进行图像识别，语音识别，自然语言处理的应用开发。课程要求同学完成一个深度学习的AI应用，为高中的科学竞赛与科研做好准备。",
     "completion": "AI 2是AI的进阶课程，主要目标是让同学从普通机器学习，过度到深度学习与神经网络的高级题目与应用中。通过课程的学习，同学已经掌握如何使用深度学习的功能库来进行图像识别，语音识别，自然语言处理的应用开发，并且完成一个深度学习的AI应用，为下面的科学竞赛与科研做好了扎实的准备。",
     "detailsUrl": "blockchainaic.html",
     "id": "5f1f5b2457e17945692b272c",
     "online": false,
     "sname": "AI 2",
     "curriculum": "ai2",
     "title1": "AI深度学习与区块链技术",
     "title2": "AI高阶编程",
     "shortName": "AI高阶编程",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "blockchainaic.html",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs440": {
     "enabled": true,
     "name": "iPhone手机APP开发与Swift编程:在Apple商店发布你的手机App",
     "imageUrl": "img/my/ios/bg-sm.jpg",
     "gradeLevel": "L4应用主题编程",
     "text": "学习流行的Swift编程语言和iOS手机App开发，在你的iPhone上运行自己的App",
     "tag": "移动互联网编程系列",
     "courseCode": "cs440",
     "suggestedCourses": [],
     "detailsUrl": "mobileiosc.html",
     "id": "5f1f5b2457e17945692b272d",
     "online": false,
     "sname": "Swift",
     "curriculum": "",
     "title1": "iPhone手机APP开发与Swift编程",
     "title2": "在Apple商店发布你的手机App",
     "shortName": "iPhone手机APP开发与Swift编程",
     "pathway": [
      "mobile"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs430": {
     "enabled": true,
     "name": "Python高阶编程:AI人工智能初步与深度学习",
     "imageUrl": "img/my/ai-bg.jpg",
     "gradeLevel": "L4应用主题编程",
     "text": "学习人工智能的初步并且动手编写实用的真正的AI应用程序",
     "tag": "编程算法与AI系列",
     "courseCode": "cs430",
     "suggestedCourses": [],
     "introduction": "AI人工智能初步是L4级别的核心课程，主要的目标是让同学开始进行编程的主题应用开发，解决实际的问题，并且可以独立的实际AI算法并融入到项目中去。本节课同学需要完成所有常用的机器学习算法与功能库，并且完成一个可以参赛的综合的AI与数据分析的项目，为下一阶段的AI 2编程做好准备。",
     "completion": "AI人工智能初步是L4级别的核心课程，通过课程的学习，同学已经可以开始进行AI编程的主题应用开发，解决实际的问题，并且可以独立的把AI算法融入到项目中去。同学已经掌握常用的机器学习算法与功能库scikit-learn，并且完成了一个可以综合的AI与数据分析的项目，为下一阶段的AI 2编程做好准备。",
     "detailsUrl": "pythonc3ai.html",
     "id": "5f1f5b2457e17945692b272e",
     "online": false,
     "sname": "AI 1",
     "curriculum": "ai1",
     "title1": "AI人工智能初步与深度学习",
     "title2": "Python高阶编程",
     "shortName": "AI人工智能初步与深度学习",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs470": {
     "enabled": true,
     "name": "电子工程师成长之路:Raspberry PI智能物联网系统编程",
     "imageUrl": "img/my/rpi/bg2.jpg",
     "gradeLevel": "L4应用主题编程",
     "text": "制作物联网电子系统，在硬件的世界学习软件，让你充分体验编程的强大",
     "tag": "移动互联网编程系列",
     "courseCode": "cs470",
     "suggestedCourses": [],
     "detailsUrl": "rpic.html",
     "id": "5f1f5b2457e17945692b272f",
     "online": false,
     "sname": "Raspberry PI",
     "curriculum": "raspberrypi",
     "title1": "Raspberry PI智能物联网系统编程",
     "title2": "电子工程师成长之路",
     "shortName": "Raspberry PI智能物联网系统编程",
     "pathway": [
      "hardware"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs461": {
     "enabled": true,
     "name": "电子工程师成长之路:Arduino硬件系统编程",
     "imageUrl": "img/my/arduino/arduino-bg-sm.jpg",
     "gradeLevel": "L4应用主题编程",
     "text": "制作智能电子系统，在硬件的世界学习软件，让你充分体验编程的强大",
     "tag": "移动互联网编程系列",
     "courseCode": "cs461",
     "suggestedCourses": [],
     "detailsUrl": "arduinoc.html",
     "id": "5f1f5b2457e17945692b2730",
     "online": false,
     "sname": "Arduino Pro",
     "curriculum": "",
     "title1": "电子工程师成长之路",
     "title2": "Arduino硬件系统编程",
     "shortName": "Arduino硬件系统编程",
     "pathway": [
      "hardware"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs482": {
     "enabled": true,
     "name": "Unreal高级开发与VR应用:专业游戏开发工程师之路",
     "imageUrl": "img/my/unreal/bg2-sm.jpg",
     "gradeLevel": "L4应用主题编程",
     "text": "学习Unreal的高级技术和技巧，做VR虚拟现实应用。",
     "tag": "游戏编程系列",
     "courseCode": "cs482",
     "suggestedCourses": [],
     "detailsUrl": "unreal2c.html",
     "id": "5f1f5b2457e17945692b2731",
     "online": false,
     "sname": "Unreal 2",
     "curriculum": "",
     "title1": "Unreal高级开发与VR应用",
     "title2": "专业游戏开发工程师之路",
     "shortName": "Unreal高级开发与VR应用",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs480": {
     "enabled": true,
     "name": "Unreal游戏引擎专业游戏开发:做你自己的Fortnite",
     "imageUrl": "img/my/unreal/bg-sm.png",
     "gradeLevel": "L4应用主题编程",
     "text": "学习世界最流行的游戏开发引擎，让你在中学就可以挥洒创意，创作出你自己想玩的游戏。",
     "tag": "游戏编程系列",
     "courseCode": "cs480",
     "suggestedCourses": [],
     "detailsUrl": "unrealc.html",
     "id": "5f1f5b2457e17945692b2732",
     "online": false,
     "sname": "Unreal 1",
     "curriculum": "",
     "title1": "Unreal游戏引擎专业游戏开发",
     "title2": "做你自己的Fortnite",
     "shortName": "Unreal游戏引擎专业游戏开发",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs485": {
     "enabled": true,
     "name": "Maya 3D动画设计与编程:动画游戏开发设计师之路",
     "imageUrl": "img/my/maya/bg.jpg",
     "gradeLevel": "L4应用主题编程",
     "text": "学习专业的3D建模与动画场景制作，艺术与编程的完美结合。",
     "tag": "游戏编程系列",
     "courseCode": "cs485",
     "suggestedCourses": [],
     "detailsUrl": "mayac.html",
     "id": "5f1f5b2457e17945692b2733",
     "online": false,
     "sname": "Maya 1",
     "curriculum": "",
     "title1": "Maya 3D动画设计与编程",
     "title2": "动画游戏开发设计师之路",
     "shortName": "Maya 3D动画设计与编程",
     "pathway": [
      "game"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs501": {
     "enabled": true,
     "name": "USACO信息学竞赛算法1:信息学介绍与算法初步",
     "imageUrl": "img/my/ioi/bg-sm.jpeg",
     "gradeLevel": "L5竞技编程",
     "text": "熟悉USACO算法基础，解决、优化实际问题，备战USACO信息学竞赛",
     "tag": "编程算法与AI系列",
     "courseCode": "cs501",
     "suggestedCourses": [],
     "introduction": "USACO 1作为L5级别核心课程，主要开始为USACO以及相关信息学竞赛做初步的准备。课程的核心目标是让同学们从编程到算法思维上的转换。课程主要包含8个基础的算法知识点，同时课程伴随完成USACO 1的50题题库，让同学进行锻炼，为更加深入的信息学竞赛打下坚实基础。",
     "completion": "USACO 1作为L5级别核心课程，主要开始为USACO以及相关信息学竞赛做初步的准备。通过该课程的学习，同学已经完成从编程到算法思维上的转换，掌握了主要的8个基础的算法知识点，同时完成USACO 1的50题题库，为更加深入的信息学竞赛打下坚实基础。",
     "detailsUrl": "ioic.html",
     "id": "5f1f5b2457e17945692b2734",
     "online": false,
     "sname": "USACO 1",
     "curriculum": "usaco50",
     "title1": "USACO信息学竞赛算法1",
     "title2": "信息学介绍与算法初步",
     "shortName": "USACO信息学竞赛算法1",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs490": {
     "enabled": true,
     "name": "计算机信息与网络安全:做黑客的终结者",
     "imageUrl": "img/my/security/bg-sm.jpeg",
     "gradeLevel": "L4应用主题编程",
     "text": "了解黑客的常见入侵原理，实验各种网络攻防技术，做合格的网络安全守护者。",
     "tag": "移动互联网编程系列",
     "courseCode": "cs490",
     "suggestedCourses": [],
     "detailsUrl": "securityc.html",
     "id": "5f1f5b2457e17945692b2735",
     "online": false,
     "sname": "Cyber Security",
     "curriculum": "",
     "title1": "计算机信息与网络安全",
     "title2": "做黑客的终结者",
     "shortName": "计算机信息与网络安全",
     "pathway": [
      "mobile"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs502": {
     "enabled": true,
     "name": "USACO信息学竞赛算法2:高级语言功能与算法介绍",
     "imageUrl": "img/my/ioi/bg-sm.jpeg",
     "gradeLevel": "L5竞技编程",
     "text": "学习高级算法，解决、优化实际问题，备战USACO信息学竞赛",
     "tag": "编程算法与AI系列",
     "courseCode": "cs502",
     "suggestedCourses": [],
     "introduction": "USACO 2作为L5级别核心课程，主要开始为USACO以及相关信息学竞赛发力。课程主要包含竞赛常考的10个算法知识点，把题目按照知识点分类，让同学进行锻炼。完成该课程后，同学基本上开始进行USACO Bronze级别的专项锻炼。",
     "completion": "USACO 2作为L5级别核心课程，主要开始为USACO以及相关信息学竞赛发力，通过这门课的完成，同学已经掌握竞赛常考的10个算法知识点，并且完成了各个题目的分类。同学目前基本上可以开始进行USACO Bronze级别的专项锻炼，准备USACO的备考。",
     "detailsUrl": "ioic.html",
     "id": "5f1f5b2457e17945692b2736",
     "online": false,
     "sname": "USACO 2",
     "curriculum": "usaco2",
     "title1": "USACO信息学竞赛算法2",
     "title2": "高级语言功能与算法强化",
     "shortName": "USACO信息学竞赛算法2",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs510": {
     "enabled": true,
     "name": "AP CS基础训练营:Java编程入门及AP课程准备",
     "imageUrl": "img/my/coding-spacesm.jpg",
     "gradeLevel": "L5竞技编程",
     "text": "帮助零编程基础的高中同学准备AP CS课程和考试所需要的扎实的编程基本功",
     "tag": "AP CS编程系列",
     "courseCode": "cs510",
     "suggestedCourses": [
      "cs515"
     ],
     "introduction": "Java 1是AP CS Java课程的系列课程的初级课程，主要教授Java语言的核心编程思想，以及基本语法与控制流程。适合高年级，尤其是打算备考AP CS Java考试的同学学习。课程完成要求同学能够独立编写基础的Java程序，为Java的进阶和面向对象编程打下基础。",
     "completion": "Java 1是AP CS Java课程的系列课程的初级课程，主要教授Java语言的核心编程思想。通过课程学习，同学已经掌握Java基本语法与控制流程，能够按照要求独立编写完成基础的Java应用程序，为Java的进阶和面向对象编程打下基础。",
     "detailsUrl": "apcs-cn.html",
     "id": "5f1f5b2457e17945692b2737",
     "online": true,
     "sname": "Java 1",
     "curriculum": "java1",
     "title1": "AP CS基础训练营",
     "title2": "Java编程入门及AP课程准备",
     "shortName": "Java编程入门及AP课程准备",
     "pathway": [
      "ap"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs505": {
     "enabled": true,
     "name": "USACO信息学竞赛挑战3:备战计算机信息学奥赛",
     "imageUrl": "img/my/ioi/bg-sm.jpeg",
     "gradeLevel": "L5竞技编程",
     "text": "挑战青少年计算机的最高级别竞赛，在竞赛中锻炼自己的程序设计能力与技巧.",
     "tag": "编程算法与AI系列",
     "courseCode": "cs505",
     "suggestedCourses": [],
     "introduction": "USACO Bronze是为了备考USACO Bronze铜级而进行的课程，主要的目标是完成USACO Bronze过去5年的所有真题，让同学在题目中找到自己的确实知识点，进行复习，并且熟悉USACO Bronze的考试难度和形式，争取在年底一次通过。",
     "completion": "USACO Bronze是为了备考USACO Bronze铜级而进行的课程，主要的目标是完成USACO Bronze过去5年的所有真题，让同学在题目中找到自己的确实知识点，进行复习，并且熟悉USACO Bronze的考试难度和形式，争取在年底一次通过。",
     "detailsUrl": "ioic.html",
     "id": "5f1f5b2457e17945692b2738",
     "online": false,
     "sname": "USACO Bronze",
     "curriculum": "usaco-b",
     "title1": "USACO信息学竞赛挑战3",
     "title2": "备战计算机信息学奥赛",
     "shortName": "USACO信息学竞赛算法3",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs520": {
     "enabled": true,
     "name": "AP CS考试冲刺训练营:AP CS备考强化训练",
     "imageUrl": "img/apcsprep/bg-sm.jpg",
     "gradeLevel": "L5竞技编程",
     "text": "为即将参加AP考试的同学复习课程重点，训练考试习题，强化考试所需要的编程基本功",
     "tag": "AP CS编程系列",
     "courseCode": "cs520",
     "suggestedCourses": [],
     "detailsUrl": "apcsprep-cn.html",
     "id": "5f1f5b2457e17945692b2739",
     "online": true,
     "sname": "Java 3",
     "curriculum": "",
     "title1": "AP CS考试冲刺训练营",
     "title2": "AP CS备考强化训练",
     "shortName": "AP CS备考强化训练",
     "pathway": [
      "ap"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs521": {
     "enabled": true,
     "name": "名校申请背景强化课程:Python基础与应用程序开发",
     "imageUrl": "img/my/pythononline.png",
     "gradeLevel": "L5竞技编程",
     "text": "学习当今最流行的编程语言，开发任何你想制作的应用程序",
     "tag": "编程算法与AI系列",
     "courseCode": "cs521",
     "suggestedCourses": [],
     "detailsUrl": "pyonline-cn.html",
     "id": "5f1f5b2457e17945692b273a",
     "online": true,
     "sname": "Python Online",
     "curriculum": "",
     "title1": "Python编程网络直播",
     "title2": "学会Python，动手编写真正的计算机应用程序",
     "shortName": "Python基础与应用程序开发",
     "pathway": [
      "coding"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs531": {
     "enabled": true,
     "name": "AP CSP手机APP编程训练营:挑战最新的AP CS课程",
     "imageUrl": "img/my/mobile-learn-0sm.jpg",
     "gradeLevel": "L5竞技编程",
     "text": "College Board的最新AP课程Computer Science Principles",
     "tag": "AP CS编程系列",
     "courseCode": "cs531",
     "suggestedCourses": [],
     "detailsUrl": "apcsp-cn.html",
     "id": "5f1f5b2457e17945692b273b",
     "online": true,
     "sname": "App Inventor",
     "curriculum": "",
     "title1": "AP CSP手机APP编程训练营",
     "title2": "挑战最新的AP CS课程",
     "shortName": "AP CSP手机APP编程训练营",
     "pathway": [
      "ap"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs560": {
     "enabled": true,
     "name": "名校申请背景强化课程:计算机编程系列手机App编程开发",
     "imageUrl": "img/my/mobile-learn-6sm.jpg",
     "gradeLevel": "L5竞技编程",
     "text": "学习App编程，为AP CS课程、科学竞赛、课外项目和创业充实内容和经历",
     "tag": "名校申请背景强化系列",
     "courseCode": "cs560",
     "suggestedCourses": [],
     "detailsUrl": "ceappc.html",
     "id": "5f1f5b2457e17945692b273c",
     "online": true,
     "sname": "App Development",
     "curriculum": "",
     "title1": "名校申请背景强化课程",
     "title2": "计算机编程系列手机App编程开发",
     "shortName": "计算机编程系列手机App编程开发",
     "pathway": [
      "ce"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs561": {
     "enabled": true,
     "name": "名校申请背景强化课程:计算机编程系列Unity3D游戏开发",
     "imageUrl": "img/my/unity3d/bg-2sm.jpg",
     "gradeLevel": "L5竞技编程",
     "text": "学习专业3D游戏开发，为AP CS课程、科学竞赛、课外项目和创业充实内容和经历",
     "tag": "名校申请背景强化系列",
     "courseCode": "cs561",
     "suggestedCourses": [],
     "detailsUrl": "ceunity3dc.html",
     "id": "5f1f5b2457e17945692b273d",
     "online": false,
     "sname": "Unity Advanced",
     "curriculum": "",
     "title1": "名校申请背景强化课程",
     "title2": "计算机编程系列Unity3D游戏开发",
     "shortName": "计算机编程系列Unity3D游戏开发",
     "pathway": [
      "ce"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs562": {
     "enabled": true,
     "name": "名校申请背景强化课程:Python竞技编程与项目实践",
     "imageUrl": "img/my/pythonmine/pyce-bg-sm.jpg",
     "gradeLevel": "L5竞技编程",
     "text": "学习Python算法，为AP CS课程、科学竞赛、课外项目和创业充实内容和经历",
     "tag": "名校申请背景强化系列",
     "courseCode": "cs562",
     "suggestedCourses": [],
     "detailsUrl": "cepythonc.html",
     "id": "5f1f5b2457e17945692b273e",
     "online": true,
     "sname": "Python Advacned Project",
     "curriculum": "",
     "title1": "名校申请背景强化课程",
     "title2": "Python竞技编程与项目实践",
     "shortName": "Python竞技编程与项目实践",
     "pathway": [
      "ce"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs563": {
     "enabled": true,
     "name": "名校申请背景强化课程:人工智能基础与项目实践",
     "imageUrl": "img/my/ceml/ai-sm.jpg",
     "gradeLevel": "L5竞技编程",
     "text": "学习Python算法，开发人工智能应用项目，为科学竞赛、课外项目和创业充实内容和经历",
     "tag": "名校申请背景强化系列",
     "courseCode": "cs563",
     "suggestedCourses": [],
     "detailsUrl": "cemlc.html",
     "id": "5f1f5b2457e17945692b273f",
     "online": true,
     "sname": "Advanced AI",
     "curriculum": "ai1",
     "title1": "名校申请背景强化课程",
     "title2": "人工智能基础与项目实践",
     "shortName": "人工智能基础与项目实践",
     "pathway": [
      "ce"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs564": {
     "enabled": true,
     "name": "名校申请背景强化课程:Technovation编程竞技与创业竞赛",
     "imageUrl": "img/my/cetech/te-bg.jpg",
     "gradeLevel": "L5竞技编程",
     "text": "学习APP编程开发，参加Technovation编程竞技与创业竞赛",
     "tag": "名校申请背景强化系列",
     "courseCode": "cs564",
     "suggestedCourses": [],
     "detailsUrl": "cetechc.html",
     "id": "5f1f5b2457e17945692b2740",
     "online": false,
     "sname": "Technovation",
     "curriculum": "",
     "title1": "名校申请背景强化课程",
     "title2": "Technovation编程竞技与创业竞赛",
     "shortName": "Technovation编程竞技与创业竞赛",
     "pathway": [
      "ce"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs570": {
     "enabled": true,
     "name": "名校申请背景强化课程:青少年科技创业项目",
     "imageUrl": "img/my/cestartup/bg-sm.png",
     "gradeLevel": "L5竞技编程",
     "text": "编程创新，学以致用，解决实际问题，做自己的创业公司",
     "tag": "名校申请背景强化系列",
     "courseCode": "cs570",
     "suggestedCourses": [],
     "introduction": "该课程适合有编程基础，有具体编程兴趣方向的同学，课程主要专注于带领同学从idea，到设计，到实现MVP项目版本的整个过程。同时，同学还要具体的考虑项目发布，商业模式等实际问题，为科技和创业竞赛打下基础。",
     "completion": "该课程适合有编程基础，有具体编程兴趣方向的同学，课程主要专注于带领同学从idea，到设计，到实现MVP项目版本的整个过程。同时，同学还要具体的考虑项目发布，商业模式等实际问题，为科技和创业竞赛打下基础。",
     "detailsUrl": "cestartupc.html",
     "id": "5f1f5b2457e17945692b2741",
     "online": false,
     "sname": "Startup",
     "curriculum": "",
     "title1": "名校申请背景强化课程",
     "title2": "青少年科技创业项目",
     "shortName": "青少年科技创业项目",
     "pathway": [
      "ce"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs565": {
     "enabled": true,
     "name": "Flutter跨平台手机App开发:同时发布Android和iOS",
     "imageUrl": "img/my/flutter/flutter.png",
     "gradeLevel": "L5竞技编程",
     "text": "学习最新跨平台手机开发，实现Android和iOS的同步支持",
     "tag": "名校申请背景强化系列",
     "courseCode": "cs565",
     "suggestedCourses": [],
     "introduction": "Flutter手机App开发是L5级别的高级编程开发课程，该课程使用Google最新的手机开发平台Flutter来高效的进行跨平台的手机App开发，学生会学习高级编程语言Dart，来编写能够同时在Android和iOS上运行的专业App，并且最终发布到Apple Store和Google Play的官方应用商店上去。",
     "completion": "Flutter手机App开发是L5级别的高级编程开发课程，通过该课程的学习，学生已经掌握了如何使用Google最新的手机开发平台Flutter来高效的进行跨平台的手机App开发。学生学习了高级编程语言Dart，并且知道如何来编写能够同时在Android和iOS上运行的专业App，并且最终完成了可以发布到Apple Store和Google Play的官方应用商店上的个人App项目。",
     "detailsUrl": "flutterc.html",
     "id": "5f1f5b2457e17945692b2742",
     "online": true,
     "sname": "Flutter",
     "curriculum": "flutter",
     "title1": "名校申请背景强化课程",
     "title2": "Flutter跨平台手机App开发",
     "shortName": "Flutter跨平台手机App开发",
     "pathway": [
      "ce"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs571": {
     "enabled": true,
     "name": "Science Fair科学竞赛强化:编程助理科学竞赛",
     "imageUrl": "img/my/cestartup/bg-sm.png",
     "gradeLevel": "L5竞技编程",
     "text": "编程创新，学以致用，解决实际问题，在科学竞赛脱颖而出",
     "tag": "名校申请背景强化系列",
     "courseCode": "cs571",
     "suggestedCourses": [],
     "detailsUrl": "sciencefairc.html",
     "id": "5f1f5b2457e17945692b2743",
     "online": false,
     "sname": "Science Fair",
     "curriculum": "",
     "title1": "Science Fair科学竞赛强化",
     "title2": "编程助理科学竞赛",
     "shortName": "Science Fair科学竞赛强化",
     "pathway": [
      "ce"
     ],
     "detailsTitle": "查看详情",
     "locations": "选择地点",
     "registerUrl": "corecn.html#allCourses",
     "registerTitle": "我要注册",
     "registerForm": "https://jinshuju.net/f/0KnUba"
    },
    "cs450": {
     "enabled": true,
     "imageUrl": "",
     "gradeLevel": "L4应用主题编程",
     "text": "",
     "tag": "",
     "courseCode": "cs450",
     "suggestedCourses": [],
     "introduction": "Web开发是L4级别应用主题系列课程之一，主要目的是让同学学习Web应用开发的基础，包括网页HTML与CSS语言，JavaScript语言基础。最终的目标是让同学可以独立做出自己的个人网站，以及初步的Web应用程序，并且发布在云端。",
     "completion": "Web开发是L4级别应用主题系列课程之一，通过该课程的学习，同学已经掌握了Web应用开发的基础，包括网页HTML与CSS语言，JavaScript语言基础。课程项目阶段，同学独立完成了自己的个人网站，以及初步的Web应用程序，并且发布在云端。",
     "detailsUrl": "",
     "id": "5f441f3b4cddb200144aca8f",
     "curriculum": "web-css",
     "shortName": "Web开发基础HTML/CSS",
     "sname": "Web 1",
     "title1": "",
     "title2": "",
     "registerUrl": ""
    },
    "cs360": {
     "enabled": true,
     "imageUrl": "",
     "gradeLevel": "L3代码编程",
     "text": "学习开发风靡全球的Roblox，发布你自己的游戏，创业编程两不误",
     "tag": "游戏编程系列",
     "courseCode": "cs360",
     "suggestedCourses": [
      "cs300"
     ],
     "introduction": "Roblox 2是L3级别的核心课程，主要的目标是让同学使用Lua更多的编写简洁的代码程序，尝试设计程序算法，并且可以独立的构思功能并融入到项目中去。本节课同学需要完成所有常用的Lua编程语言的功能特点，并且完成一个可以参赛的综合的Roblox的游戏项目，为下一阶段L3的编程学习做好准备。",
     "completion": "Roblox 2是L3级别的核心课程，主要的目标是让同学使用Lua更多的编写简洁的代码程序，尝试设计程序算法，并且可以独立的构思功能并融入到项目中去。通过本节课的完成，同学已经完成所有常用的Lua编程语言的功能特点，并且完成了一个可以参赛的综合的Roblox的游戏项目，为下一阶段L3的编程学习做好了准备。",
     "detailsUrl": "corecn.html#allCourses",
     "id": "5f443d271f76fb0014b21dda",
     "curriculum": "roblox2",
     "shortName": "Roblox游戏开发与Lua编程进阶",
     "sname": "Roblox 2",
     "title1": "Roblox游戏开发与Lua编程进阶",
     "title2": "游戏创业学编程",
     "registerUrl": ""
    },
    "cs486": {
     "enabled": true,
     "imageUrl": "",
     "gradeLevel": "L4应用主题编程",
     "text": "",
     "tag": "",
     "courseCode": "cs486",
     "suggestedCourses": [],
     "detailsUrl": "",
     "id": "5f4444edb241710014a7504d",
     "curriculum": "",
     "shortName": "Maya 3D动画设计与编程进阶",
     "sname": "Maya 2",
     "title1": "",
     "title2": "",
     "registerUrl": ""
    },
    "cs250": {
     "enabled": true,
     "imageUrl": "",
     "gradeLevel": "L2简洁代码编程",
     "text": "",
     "tag": "",
     "courseCode": "cs250",
     "suggestedCourses": [],
     "introduction": "Scratch的高阶编程属于图形化编程的后一阶段，是往简洁代码与代码编程过度的最后一个课程。该课程强调学生的综合应用能力培养，不但要求同学完成Scratch高级知识点，更重要的目标是培养同学设计编程算法和系统应用的能力北京，能够完全把自己的idea独立动手实现。",
     "completion": "Scratch的高阶编程属于图形化编程的后一阶段，是往简洁代码与代码编程过度的最后一个课程。通过课程学习，同学不但完成Scratch高级知识点，更重要的是培养了同学设计编程算法和系统应用的能力北京，使同学能够完全把自己的idea独立动手实现，为代码编程打下基础。",
     "detailsUrl": "",
     "id": "5f4c1d16a8b1f00014414e8d",
     "curriculum": "",
     "shortName": "MIT Scratch编程高阶",
     "sname": "Scratch 3",
     "title1": "MIT Scratch编程高阶",
     "title2": "",
     "registerUrl": ""
    },
    "cs515": {
     "enabled": true,
     "imageUrl": "",
     "gradeLevel": "L5竞技编程",
     "text": "",
     "tag": "",
     "courseCode": "cs515",
     "suggestedCourses": [
      "cs520"
     ],
     "introduction": "Java 2是AP CS Java课程的第二级别，主要的目标是学习Java的面向对象的核心知识点，包括类、对象、继承、接口、多态等考试要点。完成Java 2可以完成AP CS Java考试要求的所有知识点，为下面的AP CS Java备考做题打下基础。",
     "completion": "Java 2是AP CS Java课程的第二级别，通过该课程的学习，同学已经掌握了Java的面向对象的核心知识点，包括类、对象、继承、接口、多态等考试要点。同学现在已经学习完了AP CS Java考试要求的所有知识点，为下面的AP CS Java备考做题打下基础。",
     "detailsUrl": "",
     "id": "5f4c3581a8b1f00014414e9b",
     "curriculum": "java2",
     "shortName": "Java进阶与面向对象编程",
     "sname": "Java 2",
     "title1": "Java进阶与面向对象编程",
     "title2": "",
     "registerUrl": ""
    },
    "cs506": {
     "enabled": true,
     "imageUrl": "",
     "gradeLevel": "L5竞技编程",
     "text": "",
     "tag": "",
     "courseCode": "cs506",
     "suggestedCourses": [],
     "detailsUrl": "",
     "englishDetailsUrl": "",
     "id": "5f6678ccd4f7200014ebf294",
     "curriculum": "usaco-s",
     "shortName": "USACO信息学竞赛算法Silver",
     "sname": "USACO Silver",
     "title1": "",
     "title2": "",
     "registerUrl": ""
    },
    "cs575": {
      "enabled": true,
      "imageUrl": "",
      "gradeLevel": "L5竞技编程",
      "text": "",
      "tag": "",
      "courseCode": "cs575",
      "suggestedCourses": [],
      "detailsUrl": "",
      "englishDetailsUrl": "",
      "instructorDescription": "",
      "id": "5faabf72d62cb400143bd806",
      "curriculum": "",
      "shortName": "AP CS A专项辅导",
      "sname": "AP CS A Tutor",
      "pathway": "",
      "title1": "",
      "title2": "",
      "registerUrl": ""
    },
    "cs580": {
     "enabled": true,
     "imageUrl": "",
     "gradeLevel": "L5竞技编程",
     "text": "",
     "tag": "",
     "courseCode": "cs580",
     "suggestedCourses": [],
     "detailsUrl": "",
     "englishDetailsUrl": "",
     "id": "5f6e528fef553b001403115a",
     "curriculum": "",
     "shortName": "高中背景提升项目",
     "sname": "HS Project",
     "title1": "",
     "title2": "",
     "registerUrl": ""
    }
   }
   
}


var templist = []
var copy = {}
Object.keys(coursedb.cn).forEach(key=>{
	if (coursedb.cn[key].enabled===true){
		delete coursedb.cn[key].cid;
		copy = coursedb.cn[key]
		key.toLowerCase();
        copy["courseCode"] = key;
		templist.push(copy)
	}
	}
)

console.log(JSON.stringify(templist))
